const emojis = require('./../emojis');

module.exports = {
    test: `هذا نص تجريبي باللغة العربية`,
    timeout: {
        userNotFound: `**${emojis.emojis.incorrect} لم يتم العثور على المستخدم في هذا السيرفر.**`,
        invalidDuration: `**${emojis.emojis.warning} صيغة المدة غير صحيحة. استخدم صيغ مثل 10m، 1h، 1d.**`,
        durationExceed: `**${emojis.emojis.warning} لا يمكن أن تتجاوز المدة 28 يومًا.**`,
        success: {
            set: `**${emojis.emojis.correct} تم وضع مهلة للمستخدم {{user}} لمدة {{duration}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
            remove: `**${emojis.emojis.correct} تمت إزالة المهلة عن المستخدم {{user}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} فشل في إعطاء مهلة للمستخدم. هل لدي الصلاحيات الصحيحة؟ تأكد أن رتبتي أعلى من رتبة المستخدم.\n-# إذا استمرت المشكلة، يرجى التواصل مع الدعم.**`,
        cannotSelf: `**${emojis.emojis.warning} لا يمكنك إعطاء مهلة لنفسك.**`,
        cannotBot: `**${emojis.emojis.warning} لا يمكنك إعطائي مهلة.**`,
        cannotHigher: `**${emojis.emojis.warning} لا يمكنك إعطاء مهلة لعضو رتبته مساوية أو أعلى من رتبتك.**`,
        cannotModerate: `**${emojis.emojis.warning} لا أستطيع إعطاء مهلة لهذا المستخدم. ربما رتبته أعلى مني أو لديه صلاحيات المدير.**`,
        invalidAction: `**${emojis.emojis.incorrect} إجراء غير صالح. استخدم 'set' أو 'remove'.**`,
    },
    ban: {
        userNotFound: `**${emojis.emojis.incorrect} لم يتم العثور على المستخدم في هذا السيرفر.**`,
        success: {
            give: `**${emojis.emojis.correct} تم حظر {{user}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
            remove: `**${emojis.emojis.correct} تم إلغاء حظر {{user}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} فشل في حظر/إلغاء حظر المستخدم. هل لدي الصلاحيات الصحيحة؟ تأكد أن رتبتي أعلى من رتبة المستخدم.\n-# إذا استمرت المشكلة، يرجى التواصل مع الدعم.**`,
        cannotSelf: `**${emojis.emojis.warning} لا يمكنك حظر نفسك.**`,
        cannotBot: `**${emojis.emojis.warning} لماذا؟ تواصل مع سيرفر الدعم للمزيد من المساعدة.**`,
        cannotHigher: `**${emojis.emojis.warning} لا يمكنك حظر عضو رتبته مساوية أو أعلى من رتبتك.**`,
        cannotModerate: `**${emojis.emojis.warning} لا أستطيع حظر هذا المستخدم. ربما رتبته أعلى مني أو لديه صلاحيات المدير.**`,
        invalidAction: `**${emojis.emojis.incorrect} إجراء غير صالح. استخدم 'give' أو 'remove'.**`,
        alreadyBanned: `**${emojis.emojis.warning} هذا المستخدم محظور بالفعل.**`,
    },
    kick: {
        userNotFound: `**${emojis.emojis.incorrect} لم يتم العثور على المستخدم في هذا السيرفر.**`,
        kicked: `**${emojis.emojis.correct} تم طرد {{user}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} فشل في طرد المستخدم. هل لدي الصلاحيات الصحيحة؟ تأكد أن رتبتي أعلى من رتبة المستخدم.\n-# إذا استمرت المشكلة، يرجى التواصل مع الدعم.**`,
        cannotSelf: `**${emojis.emojis.warning} لا يمكنك طرد نفسك.**`,
        cannotBot: `**${emojis.emojis.warning} لا يمكنك طردي.**`,
        cannotHigher: `**${emojis.emojis.warning} لا يمكنك طرد عضو رتبته مساوية أو أعلى من رتبتك.**`,
        botCannotHigher: `**${emojis.emojis.warning} لا أستطيع طرد عضو رتبته مساوية أو أعلى من رتبتي.**`,
        cannotModerate: `**${emojis.emojis.warning} لا أستطيع طرد هذا المستخدم. ربما رتبته أعلى مني أو لديه صلاحيات المدير.**`,
    },
    unban: {
        userNotFound: `**${emojis.emojis.incorrect} لم يتم توفير معرف المستخدم.**`,
        userNotBanned: `**${emojis.emojis.warning} هذا المستخدم غير محظور.**`,
        unbanned: `**${emojis.emojis.correct} تم إلغاء حظر {{user}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} فشل في إلغاء حظر المستخدم. الخطأ: {{error}}**`,
    },
    lock: {
        channelNotFound: `**${emojis.emojis.incorrect} لم يتم العثور على القناة.**`,
        locked: `**${emojis.emojis.correct} تم قفل {{channel}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
        alreadyLocked: `**${emojis.emojis.warning} هذه القناة مقفلة بالفعل.**`,
        error: `**${emojis.emojis.incorrect} فشل في قفل القناة. هل لدي الصلاحيات الصحيحة?\n-# إذا استمرت المشكلة، يرجى التواصل مع الدعم.**`,
        cannotLock: `**${emojis.emojis.warning} لا أستطيع قفل هذه القناة. هل لدي الصلاحيات الصحيحة؟**`,
    },
    unlock: {
        channelNotFound: `**${emojis.emojis.incorrect} لم يتم العثور على القناة.**`,
        unlocked: `**${emojis.emojis.correct} تم فتح {{channel}} بنجاح. ${emojis.emojis.reason} السبب: {{reason}}**`,
        notLocked: `**${emojis.emojis.warning} هذه القناة غير مقفلة.**`,
        error: `**${emojis.emojis.incorrect} فشل في فتح القناة. هل لدي الصلاحيات الصحيحة?\n-# إذا استمرت المشكلة، يرجى التواصل مع الدعم.**`,
        cannotUnlock: `**${emojis.emojis.warning} لا أستطيع فتح هذه القناة. هل لدي الصلاحيات الصحيحة؟**`,
    },

    avatar: {
        onlyInServer: `**${emojis.emojis.warning} هذا الأمر يمكن استخدامه في السيرفر فقط!**`,
        noIcon: `**${emojis.emojis.warning} هذا السيرفر ليس لديه أيقونة!**`,
        noAvatar: `**${emojis.emojis.warning} المستخدم {{user}} ليس لديه صورة رمزية!**`,
        avatar: `صورة الملف الشخصي لـ `,
        requestedBy: `بواسطة`,
        errorFetching: `**${emojis.emojis.warning} حدث خطأ أثناء جلب الصورة الرمزية!**`,
        invalidUser: `**${emojis.emojis.warning} مستخدم غير صالح!**`,
        type: `النوع:`,
        icon: `أيقونة السيرفر لـ `,
        avatarTypes: {
            static: `ثابتة (PNG)`,
            animated: `متحركة (GIF)`,
        },
        qualityDownload: {
            sd: `تحميل SD`,
            hd: `تحميل HD`,
            uhd: `تحميل 4K`,
        },
    },

    banner: {
        onlyInServer: `**${emojis.emojis.warning} هذا الأمر يمكن استخدامه في السيرفر فقط!**`,
        noBanner: `**${emojis.emojis.warning} هذا السيرفر ليس لديه بانر!**`,
        banner: `بانر السيرفر لـ `,
        requestedBy: `بواسطة`,
        errorFetching: `**${emojis.emojis.warning} حدث خطأ أثناء جلب الصورة!**`,
        invalidUser: `**${emojis.emojis.warning} مستخدم غير صالح!**`,
        type: `النوع:`,
        accentColor: `اللون:`,
        userBanner: `بانر `,
        global: `عام`,
        bannerTypes: {
            static: `ثابتة (PNG)`,
            animated: `متحركة (GIF)`,
        },
        qualityDownload: {
            sd: `تحميل SD`,
            hd: `تحميل HD`,
            uhd: `تحميل 4K`,
        },
    },

    // مشترك / عبارات شائعة
    common: {
        coins: `عملة`,
        captchaFailed: `**${emojis.emojis.warning} فشل في إنشاء صورة التحقق. حاول مرة أخرى.**`,
        captchaPrompt: `${emojis.emojis.loading} اكتب الأحرف الموضحة في الصورة أدناه خلال **{{seconds}} ثانية**.`,
        captchaIncorrect: `**${emojis.emojis.warning} رمز التحقق غير صحيح.**`,
        captchaTimeout: `**${emojis.emojis.warning} انتهت مهلة التحقق.**`,
        entered: `أدخلت`,
        expected: `المتوقع`,
        nothing: `لا شيء`,
        noReason: `لم يتم تحديد سبب`,
        underDevelopment: `**${emojis.emojis.warning} هذا الأمر قيد التطوير.**`,
    },

    economy: {
        balance: {
            title: `الملف الاقتصادي لـ {{user}}`,
            wallet: `رصيد المحفظة`,
            bank: `رصيد البنك`,
            total: `إجمالي الثروة`,
            transactions: `العمليات الأخيرة`,
            noTransactions: `لا توجد عمليات حديثة.`,
            requestedBy: `بواسطة`,
            cooldown: `المكافأة اليومية`,
            ready: `جاهزة للاستلام!`,
            notReady: `متاحة خلال {{time}}`,
        },
        buttons: {
            refresh: `تحديث`,
            transactions: `العمليات`,
            back: `رجوع`,
            daily: `استلام المكافأة`,
        },
        transfer: {
            success: `تم التحويل بنجاح.`,
            recipient: `المستلم`,
            received: `تم الاستلام`,
            tax: `الضريبة (5%)`,
            totalSent: `إجمالي المرسل`,
            insufficient: `ليس لديك رصيد كافٍ!`,
            invalidAmount: `مبلغ غير صالح. أدخل رقمًا صحيحًا أكبر من 0 (الكسور غير مسموحة).`,
            selfTransfer: `فشل التحويل: لا يمكنك إرسال عملات لنفسك.`,
            botTransfer: `فشل التحويل: لا يمكن للحسابات الآلية استلام العملات.`,
            accountTooNew: `تم حظر التحويل: يجب أن يكون عمر حسابك في ديسكورد 30 يومًا على الأقل.`,
            recipientTooNew: `تم حظر التحويل: يجب أن يكون عمر حساب المستلم 30 يومًا على الأقل.`,
            insufficientBalance: `فشل التحويل: رصيد غير كافٍ.\nرصيدك الحالي: **{{balance}}** عملة.`,
            captchaRequired: `التحقق من التحويل مطلوب.`,
            captchaChannel: `فشل التحويل: يجب إجراء التحقق في قناة نصية في السيرفر.`,
            captchaFailed: `فشل التحويل: لم يتم إنشاء صورة التحقق. حاول مرة أخرى.`,
            captchaTimeout: `تم إلغاء التحويل: انتهت مهلة التحقق.`,
            captchaIncorrect: `تم إلغاء التحويل: رمز التحقق غير صحيح.`,
            captchaHint: `تأكد من كتابة الأحرف الستة الموضحة في الصورة فقط.`,
            balanceChanged: `تم إلغاء التحويل: تغير رصيدك أثناء التحقق.\nالرصيد الحالي: **{{balance}}** عملة.`,
            reason: `السبب: {{reason}}`,
            // إشعار الرسائل الخاصة
            dmGreetings: [
                `لقد استلمت تحويلًا واردًا بقيمة {{amount}} عملة فلفرا من {{sender}}`,
                `تشا-تشينغ! استلمت للتو {{amount}} عملة فلفرا من {{sender}}!`,
                `أخبار سارة! أرسل لك {{sender}} مبلغ {{amount}} عملة فلفرا.`,
                `تنبيه تحويل! قام {{sender}} بتحويل {{amount}} عملة فلفرا إليك.`,
            ],
            dmTransferType: `نوع التحويل: بدون`,
            dmReason: `السبب`,
        },
        daily: {
            verification: `التحقق من المكافأة اليومية`,
            alreadyClaimed: `لقد استلمت مكافأتك اليومية بالفعل! عد بعد **{{time}}**.`,
            success: `تم استلام المكافأة اليومية بنجاح!`,
            received: `حصلت على **{{amount}}** عملة.`,
            newBalance: `رصيدك الجديد: **{{balance}}** عملة.`,
            cancelledIncorrect: `تم إلغاء الاستلام: رمز التحقق غير صحيح.`,
            cancelledTimeout: `تم إلغاء الاستلام: انتهت مهلة التحقق.`,
        },
        reputation: {
            verification: `التحقق من السمعة`,
            cannotBot: `لا يمكنك إعطاء سمعة للبوتات.`,
            cannotSelf: `لا يمكنك إعطاء سمعة لنفسك.`,
            alreadyGiven: `لقد أعطيت سمعة مؤخرًا! عد بعد **{{time}}**.`,
            success: `أعطيت نقطة سمعة لـ **{{user}}** بنجاح!\nلديه الآن **{{count}}** سمعة.`,
            cancelledIncorrect: `تم إلغاء السمعة: رمز التحقق غير صحيح.`,
            cancelledTimeout: `تم إلغاء السمعة: انتهت مهلة التحقق.`,
            // إشعار الرسائل الخاصة
            dmReceived: `لقد حصلت على نقطة سمعة من {{sender}}!`,
            dmTotal: `لديك الآن {{count}} نقطة سمعة.`,
        },
    },

    giveaway: {
        verification: `التحقق من إجراء الهدية`,
        verificationPrompt: `اكتب الأحرف في الصورة للمتابعة مع أمر **{{action}}**.`,
        verificationFailed: `فشل التحقق.`,
        verificationTimeout: `انتهت مهلة التحقق.`,
        captchaFailed: `فشل في إنشاء رمز التحقق الأمني. حاول مرة أخرى.`,
        error: `حدث خطأ أثناء تنفيذ أمر الهدية.`,
        start: {
            invalidDuration: `صيغة المدة غير صحيحة. استخدم: 1d، 2h، 15m، 30s`,
            embedTitle: `🎉 {{prize}}`,
            enterPrompt: `اضغط على زر 🎉 أدناه للمشاركة!`,
            winners: `الفائزون`,
            host: `المستضيف`,
            ends: `ينتهي`,
            enterButton: `شارك`,
            footer: `هدية`,
            success: `تم بدء الهدية في {{channel}}!`,
        },
        end: {
            notFound: `لم يتم العثور على الهدية في هذا السيرفر.`,
            notRunning: `هذه الهدية انتهت بالفعل أو تم إلغاؤها.`,
            ended: `انتهت الهدية`,
            endedAnnouncement: `🎉 **انتهت الهدية!** الفائز(ون): {{winners}}`,
            noEntrants: `لم يشارك أحد.`,
            none: `لا يوجد`,
            success: `تم إنهاء الهدية بنجاح.`,
        },
        reroll: {
            notFound: `لم يتم العثور على الهدية.`,
            notFinished: `يجب أن تنتهي الهدية لإعادة السحب.`,
            announcement: `🔄 **إعادة سحب!** الفائز(ون) الجدد لـ **{{prize}}**: {{winners}}`,
            noEntrants: `لا يوجد مشاركون صالحون للاختيار منهم.`,
            success: `تم إعادة سحب الهدية.`,
        },
        remove: {
            notFound: `لم يتم العثور على الهدية.`,
            success: `تم حذف هدية **{{prize}}** من قاعدة البيانات.`,
        },
        list: {
            title: `الهدايا النشطة`,
            noActive: `لا توجد هدايا نشطة في هذا السيرفر.`,
        },
        enter: {
            alreadyEnded: `هذه الهدية انتهت بالفعل!`,
            alreadyEntered: `لقد شاركت في هذه الهدية بالفعل!`,
            success: `🎉 تم تسجيل مشاركتك في الهدية بنجاح!`,
        },
    },

    server: {
        helpMENUtitle: `قائمة مساعدة فلفرا`,
        helpMENUdesc: `اختر فئة أدناه لاستكشاف الأوامر.`,
        selectCATEGORY: `اختر فئة`,
        selectCOMMAND: `اختر أمرًا`,
        cmdNAME: `الأمر:`,
        noDescription: `لا يوجد وصف.`,
        usage: `الاستخدام`,
        category: `الفئة`,
        type: `النوع`,
        cooldown: `مدة الانتظار`,
        none: `لا يوجد`,
        userPerms: `صلاحيات المستخدم`,
        botPerms: `صلاحيات البوت`,
        aliases: `الأسماء البديلة`,
        info: `المجموع: {{slash}} سلاش | {{prefix}} بريفكس`,
        slash: `سلاش`,
        prefix: `بريفكس`,
        push: `دفع`,
        and: `و`,
        unknown: `غير معروف`,
        commandNotFOUND: `الأمر \`{{command}}\` غير موجود.`,
        serverINFO: `معلومات السيرفر`,
        serverName: `اسم السيرفر`,
        serverID: `معرف السيرفر`,
        owner: `المالك`,
        memberCount: `الأعضاء`,
        creationDate: `تاريخ الإنشاء`,
        boostLevel: `حالة التعزيز`,
        boosts: `المستوى {{level}} ({{boostsCount}} تعزيزات)`,
        totalRoles: `الأدوار`,
        totalChannels: `القنوات`,
        region: `المنطقة`,
        requestedBy: `بواسطة`,
        onlyInServer: `هذا الأمر يمكن استخدامه في السيرفر فقط!`,
    },

    clear: {
        noTextChannel: `هذا الأمر يمكن استخدامه في القنوات النصية فقط.`,
        title: `ملخص الحذف`,
        channel: `القناة`,
        requested: `المطلوب`,
        filtered: `المصفى`,
        deleted: `المحذوف`,
        bulk: `جماعي`,
        singleOld: `فردي (قديم)`,
        errors: `أخطاء`,
        reason: `السبب: {{reason}}`,
        deletedNotice: `تم حذف {{count}} رسالة.`,
        noReason: `لم يتم تحديد سبب`,
    },

    warn: {
        guildRequired: `يجب استخدام هذا الأمر في سيرفر.`,
        userNotFound: `لم يتم العثور على المستخدم في السيرفر.`,
        cannotHigher: `لا يمكنك تحذير هذا المستخدم بسبب تسلسل الأدوار.`,
        title: `تم تحذير المستخدم`,
        user: `المستخدم`,
        infractionId: `معرف المخالفة`,
        activeWarnings: `التحذيرات النشطة`,
        reason: `السبب`,
        moderator: `المشرف`,
        dmNotice: `لقد تلقيت تحذيرًا في **{{guild}}**. السبب: {{reason}} (المعرف: {{id}})`,
        noReason: `لم يتم تحديد سبب`,
    },

    warnings: {
        guildRequired: `يجب استخدام هذا الأمر في سيرفر.`,
        title: `تحذيرات {{user}}`,
        noWarningsActive: `لا توجد تحذيرات نشطة لهذا المستخدم.`,
        noWarningsAll: `لم يتم العثور على تحذيرات (بما في ذلك غير النشطة).`,
        active: `نشط`,
        inactive: `غير نشط`,
        removed: `تمت الإزالة`,
        totalReturned: `الإجمالي المعروض`,
        includingInactive: `شامل غير النشطة`,
        yes: `نعم`,
        no: `لا`,
        requestedBy: `بواسطة {{user}}`,
    },

    warnRemove: {
        title: `تم إلغاء التحذير`,
        notFound: `لم يتم العثور على التحذير.`,
        alreadyInactive: `هذا التحذير غير نشط بالفعل.`,
        remainingActive: `المتبقي النشط`,
        userId: `معرف المستخدم`,
        removalReason: `سبب الإزالة`,
        noReason: `لم يتم تحديد سبب`,
    },

    role: {
        onlyInServer: `هذا الأمر يمكن استخدامه في السيرفر فقط!`,
        mustSpecifyRole: `يجب تحديد دور.`,
        userNotFound: `لم يتم العثور على المستخدم في هذا السيرفر.`,
        alreadyHasRole: `هذا المستخدم لديه هذا الدور بالفعل.`,
        doesNotHaveRole: `هذا المستخدم ليس لديه هذا الدور.`,
        giveSuccess: `تم إعطاء الدور {{role}} لـ {{user}} بنجاح. السبب: {{reason}}`,
        removeSuccess: `تم إزالة الدور {{role}} من {{user}} بنجاح. السبب: {{reason}}`,
        giveFail: `فشل في إعطاء الدور. هل لدي الصلاحيات الصحيحة؟ تأكد أن رتبتي أعلى من الدور المراد تعيينه.\n-# إذا استمرت المشكلة، يرجى التواصل مع الدعم.`,
        removeFail: `فشل في إزالة الدور. هل لدي الصلاحيات الصحيحة؟ تأكد أن رتبتي أعلى من الدور المراد إزالته.\n-# إذا استمرت المشكلة، يرجى التواصل مع الدعم.`,
        giveBotSuccess: `تم إعطاء الدور {{role}} لـ {{success}} بوت بنجاح. فشل في {{fail}} بوت. السبب: {{reason}}`,
        removeBotSuccess: `تم إزالة الدور {{role}} من {{success}} بوت بنجاح. فشل في {{fail}} بوت. السبب: {{reason}}`,
        giveAllSuccess: `تم إعطاء الدور {{role}} لـ {{success}} عضو بنجاح. فشل في {{fail}} عضو. السبب: {{reason}}`,
        removeAllSuccess: `تم إزالة الدور {{role}} من {{success}} عضو بنجاح. فشل في {{fail}} عضو. السبب: {{reason}}`,
        mustSpecifyTarget: `يجب تحديد مستخدم، أو اختيار التطبيق على جميع البوتات أو الأعضاء.`,
        noReason: `لم يتم تحديد سبب`,
    },

    slowmode: {
        noTextChannel: `القناة المستهدفة يجب أن تكون قناة نصية.`,
        invalidDuration: `صيغة المدة غير صحيحة. استخدم مثل: 10s، 5m، 2h، 1d، أو 0 للإلغاء.`,
        noChildChannels: `لم يتم العثور على قنوات نصية فرعية في هذه الفئة.`,
        title: `⏱ تم تحديث الوضع البطيء`,
        newRateLimit: `الحد الجديد`,
        channelsUpdated: `القنوات المحدثة`,
        failed: `فشل`,
        errors: `أخطاء`,
        reason: `السبب: {{reason}}`,
        appliedToCategory: `تم التطبيق على الفئة: **{{name}}**`,
        channel: `القناة`,
        noReason: `لم يتم تحديد سبب`,
    },

    nickname: {
        userNotFound: `لم يتم العثور على المستخدم في هذا السيرفر.`,
        cannotSelf: `لا يمكنك تغيير لقبك بهذا الأمر.`,
        cannotBot: `لا يمكنك تغيير لقب البوت.`,
        cannotHigher: `لا يمكنك إدارة عضو رتبته مساوية أو أعلى من رتبتك.`,
        cannotModerate: `لا أستطيع إدارة لقب هذا المستخدم. ربما رتبته أعلى مني.`,
        successReset: `تم إعادة تعيين لقب {{user}} بنجاح.`,
        successSet: `تم تغيير لقب {{user}} إلى **{{nickname}}** بنجاح.`,
        error: `فشل في تغيير لقب {{user}}: {{error}}`,
    },

    disconnect: {
        no_reason: `لم يتم تحديد سبب`,
        not_found: `لم يتم العثور على المستخدم.`,
        not_in_voice: `هذا المستخدم ليس في قناة صوتية.`,
        owner: `لا يمكنك قطع اتصال مالك السيرفر.`,
        higher_user: `لا يمكنك قطع اتصال عضو رتبته مساوية أو أعلى من رتبتك.`,
        higher_bot: `لا أستطيع قطع اتصال هذا المستخدم. رتبته أعلى مني.`,
        user_title: `تم قطع اتصال المستخدم`,
        user_desc: `تم قطع اتصال **{user}** من الصوت.`,
        channel: `القناة`,
        moderator: `المشرف`,
        reason: `السبب`,
        failed: `فشل في قطع الاتصال: {error}`,
        invalid_channel: `هذه القناة ليست قناة صوتية.`,
        empty_channel: `لا يوجد أعضاء في هذه القناة الصوتية.`,
        mass_title: `قطع اتصال جماعي`,
        mass_desc: `تم قطع اتصال جميع المستخدمين من **{channel}**.`,
        success: `تم قطع الاتصال`,
        no_premium: `**${emojis.emojis.warning} هذه الميزة تتطلب اشتراكًا مميزًا. يرجى الترقية لاستخدام قطع الاتصال الجماعي.**`
    },

    addemoji: {
        invalidFileType: `نوع ملف غير صالح. المسموح: {types}`,
        fileTooLarge: `الملف كبير جدًا. الحد الأقصى: {max}KB`,
        invalidSource: `مصدر غير صالح. قدم رابطًا أو إيموجي موجود.`,
        urlInvalidType: `الرابط يشير لنوع ملف غير صالح. المسموح: {types}`,
        fileTooBigRemote: `الملف البعيد كبير جدًا. الحد الأقصى: {max}KB`,
        mustProvideSource: `يجب توفير مصدر (رابط، إيموجي، أو ملف مرفق).`,
        emojiSuccessTitle: `تم إضافة الإيموجي`,
        emojiSuccessDesc: `تم إضافة {emoji} باسم **{name}**`,
        emojiFail: `فشل في إضافة الإيموجي: {error}`,
        missingTags: `يجب توفير وسوم إيموجي يونيكود صالحة.`,
        mustProvideSticker: `يجب توفير مصدر (رابط أو ملف مرفق) للملصق.`,
        stickerSuccessTitle: `تم إضافة الملصق`,
        stickerSuccessDesc: `تم إضافة الملصق **{name}**`,
        stickerFail: `فشل في إضافة الملصق: {error}`,
    },

    leveling: {
        underDevelopment: `هذا الأمر قيد التطوير.`,
        quest: {
            authorTitle: `المهام اليومية لـ {{user}}`,
            title: `مهامك اليومية`,
            description: `أكمل أنشطتك اليومية لكسب **XP** و **عملات**!\nواصل التقدم وتصدر قائمة المتصدرين! 💪`,
            messagesTitle: `الرسائل`,
            messagesGoal: `الهدف`,
            messagesReward: `المكافأة`,
            messagesProgress: `التقدم`,
            voiceTitle: `النشاط الصوتي`,
            voiceGoal: `الهدف`,
            voiceReward: `المكافأة`,
            voiceProgress: `التقدم`,
            footer: `مهام فلفرا`,
        },
    },

    ping: {
        pinging: `جاري الاتصال...`,
        networkError: `خطأ في الشبكة`,
        excellent: `ممتاز`,
        good: `جيد`,
        high: `مرتفع`,
        severeLag: `تأخير شديد`,
        pong: `🏓 بونج!`,
        wsPingTitle: `📡 استجابة الويب سوكيت`,
        msgLatencyTitle: `⏱️ تأخير الرسالة`,
    },

    backup: {
        error: `حدث خطأ غير متوقع أثناء معالجة أمر النسخ الاحتياطي. حاول مرة أخرى لاحقًا.`,
        create: {
            title: `تم إنشاء النسخة الاحتياطية بنجاح`,
            description: `تم إنشاء النسخة الاحتياطية لسيرفرك وهي جاهزة للاستعادة.`,
            backupId: `معرف النسخة`,
            rolesCaptured: `الأدوار المحفوظة`,
            channelsCaptured: `القنوات المحفوظة`,
            bansCaptured: `الحظر المحفوظ`,
            archiveSize: `حجم الأرشيف`,
            createdAt: `تاريخ الإنشاء`,
            createdBy: `تم الإنشاء بواسطة {{user}}`,
            failed: `حدث خطأ أثناء إنشاء النسخة الاحتياطية. حاول مرة أخرى لاحقًا.`,
        },
        info: {
            title: `معلومات النسخة الاحتياطية`,
            crossGuild: `هذه النسخة موجودة ولكنها تابعة لسيرفر آخر.`,
            notFound: `لم يتم العثور على معرف النسخة المحدد.`,
            rolesStored: `الأدوار المخزنة`,
            channelsStored: `القنوات المخزنة`,
            bansStored: `الحظر المخزن`,
            createdBy: `أنشأها`,
            created: `تاريخ الإنشاء`,
        },
        list: {
            title: `نسخ السيرفر الاحتياطية`,
            noBackups: `لا توجد نسخ احتياطية لهذا السيرفر بعد. استخدم \`/backup create\` لإنشاء أول نسخة!`,
            gettingStarted: `إنشاء نسخ احتياطية منتظمة يساعد في حماية إعدادات سيرفرك.`,
            description: `إليك أحدث النسخ الاحتياطية لسيرفرك:`,
            available: `النسخ المتاحة`,
        },
        load: {
            confirmRequired: `يجب تعيين \`confirm\` إلى \`true\` للمتابعة مع استعادة النسخة الاحتياطية.`,
            notFound: `لم يتم العثور على معرف النسخة المحدد.`,
            unavailable: `لا يمكن استعادة هذه النسخة الآن. الحالة: {{status}}`,
            empty: `هذه النسخة لا تحتوي على محتوى قابل للاستعادة.`,
            crossGuildWarning: `هذه النسخة تم إنشاؤها في سيرفر آخر. قد لا يتم استعادة بعض العناصر بشكل مثالي.`,
            title: `استعادة النسخة الاحتياطية`,
            instructions: `اختر المكونات التي تريد استعادتها من القائمة أدناه.`,
            selectPlaceholder: `اختر الأقسام للاستعادة (اختياري)`,
            continueBtn: `متابعة`,
            cancelBtn: `إلغاء`,
            canceled: `تم إلغاء عملية الاستعادة.`,
            purgeChannels: `جاري حذف القنوات والفئات الحالية...`,
            purgeRoles: `جاري حذف الأدوار الحالية...`,
            completedTitle: `اكتملت الاستعادة بنجاح`,
            restoredComponents: `المكونات المسترجعة`,
            resultsSummary: `ملخص النتائج`,
            purgeSummary: `ملخص الحذف`,
            issues: `مشاكل واجهتنا`,
            noIssues: `اكتملت جميع العمليات بدون مشاكل!`,
            failed: `**فشلت عملية الاستعادة**\nحدث خطأ غير متوقع أثناء عملية الاستعادة. يرجى المحاولة مرة أخرى أو الاتصال بمسؤول للحصول على المساعدة.`,
            commandChannelContext: `سياق القناة`,
            commandChannelPreserved: `🛟 تم الاحتفاظ بقناة الأوامر للسماح بالردود على التفاعل.`,
            commandChannelNotPreserved: `لم يتم الاحتفاظ بقناة الأوامر.`,
        },
        cancel: {
            noActive: `لا توجد عمليات إنشاء نسخ احتياطية قيد التشغيل.`,
            success: `تم إلغاء إنشاء النسخة الاحتياطية \`{{id}}\`.`,
        },
        delete: {
            notFound: `لم يتم العثور على معرف النسخة المحدد.`,
            alreadyDeleted: `هذه النسخة تم حذفها بالفعل.`,
            success: `تم حذف النسخة الاحتياطية \`{{id}}\`.`,
        },
    },
};
