const emojis = require('./../emojis');

module.exports = {
    test: `This is a test string in English`,
    timeout: {
        userNotFound: `**${emojis.emojis.incorrect} User not found in this guild.**`,
        invalidDuration: `**${emojis.emojis.warning} Invalid duration format. Use formats like 10m, 1h, 1d.**`,
        durationExceed: `**${emojis.emojis.warning} Duration cannot exceed 28 days.**`,
        success: {
            set: `**${emojis.emojis.correct} Successfully timed out {{user}} for {{duration}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
            remove: `**${emojis.emojis.correct} Successfully removed timeout from {{user}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} Failed to timeout the user. Do I have the correct permissions? Make sure my role is higher than the user's role.\n-# If the problem persists, please contact support.**`,
        cannotSelf: `**${emojis.emojis.warning} You cannot timeout yourself.**`,
        cannotBot: `**${emojis.emojis.warning} You cannot timeout me.**`,
        cannotHigher: `**${emojis.emojis.warning} You cannot timeout a member with an equal or higher role than yours.**`,
        cannotModerate: `**${emojis.emojis.warning} I cannot timeout this user. They might have a higher role than me or have administrator permissions.**`,
        invalidAction: `**${emojis.emojis.incorrect} Invalid action. Use 'set' or 'remove'.**`,
    },
    ban: {
        userNotFound: `**${emojis.emojis.incorrect} User not found in this guild.**`,
        success: {
            give: `**${emojis.emojis.correct} Successfully banned {{user}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
            remove: `**${emojis.emojis.correct} Successfully unbanned {{user}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} Failed to ban/unban the user. Do I have the correct permissions? Make sure my role is higher than the user's role.\n-# If the problem persists, please contact support.**`,
        cannotSelf: `**${emojis.emojis.warning} You cannot ban yourself.**`,
        cannotBot: `**${emojis.emojis.warning} Why? reach out our support server for more help.**`,
        cannotHigher: `**${emojis.emojis.warning} You cannot ban a member with an equal or higher role than yours.**`,
        cannotModerate: `**${emojis.emojis.warning} I cannot ban this user. They might have a higher role than me or have administrator permissions.**`,
        invalidAction: `**${emojis.emojis.incorrect} Invalid action. Use 'give' or 'remove'.**`,
        alreadyBanned: `**${emojis.emojis.warning} This user is already banned.**`,
    },
    kick: {
        userNotFound: `**${emojis.emojis.incorrect} User not found in this guild.**`,
        kicked: `**${emojis.emojis.correct} Successfully kicked {{user}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} Failed to kick the user. Do I have the correct permissions? Make sure my role is higher than the user's role.\n-# If the problem persists, please contact support.**`,
        cannotSelf: `**${emojis.emojis.warning} You cannot kick yourself.**`,
        cannotBot: `**${emojis.emojis.warning} You cannot kick me.**`,
        cannotHigher: `**${emojis.emojis.warning} You cannot kick a member with an equal or higher role than yours.**`,
        botCannotHigher: `**${emojis.emojis.warning} I cannot kick a member with an equal or higher role than mine.**`,
        cannotModerate: `**${emojis.emojis.warning} I cannot kick this user. They might have a higher role than me or have administrator permissions.**`,
    },
    unban: {
        userNotFound: `**${emojis.emojis.incorrect} User ID not provided.**`,
        userNotBanned: `**${emojis.emojis.warning} This user is not banned.**`,
        unbanned: `**${emojis.emojis.correct} Successfully unbanned {{user}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} Failed to unban the user. Error: {{error}}**`,
    },
    lock: {
        channelNotFound: `**${emojis.emojis.incorrect} Channel not found.**`,
        locked: `**${emojis.emojis.correct} Successfully locked {{channel}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
        alreadyLocked: `**${emojis.emojis.warning} This channel is already locked.**`,
        error: `**${emojis.emojis.incorrect} Failed to lock the channel. Do I have the correct permissions?\n-# If the problem persists, please contact support.**`,
        cannotLock: `**${emojis.emojis.warning} I cannot lock this channel. Do I have the correct permissions?**`,
    },
    unlock: {
        channelNotFound: `**${emojis.emojis.incorrect} Channel not found.**`,
        unlocked: `**${emojis.emojis.correct} Successfully unlocked {{channel}}. ${emojis.emojis.reason} Reason: {{reason}}**`,
        notLocked: `**${emojis.emojis.warning} This channel is not locked.**`,
        error: `**${emojis.emojis.incorrect} Failed to unlock the channel. Do I have the correct permissions?\n-# If the problem persists, please contact support.**`,
        cannotUnlock: `**${emojis.emojis.warning} I cannot unlock this channel. Do I have the correct permissions?**`,
    },

    avatar: {
        onlyInServer: `**${emojis.emojis.warning} This command can only be used in a server!**`,
        noIcon: `**${emojis.emojis.warning} This server doesn't have an icon set!**`,
        noAvatar: `**${emojis.emojis.warning} User {{user}} doesn't have an avatar!**`,
        avatar: `'s Avatar`,
        requestedBy: `Requested by`,
        errorFetching: `**${emojis.emojis.warning} An error occurred while fetching the avatar!**`,
        invalidUser: `**${emojis.emojis.warning} Invalid user provided!**`,
        type: `Type:`,
        icon: `'s Server Icon`,
        avatarTypes: {
            static: `Static (PNG)`,
            animated: `Animated (GIF)`,
        },
        qualityDownload: {
            sd: `Download SD`,
            hd: `Download HD`,
            uhd: `Download 4K`,
        },
    },

    banner: {
        onlyInServer: `**${emojis.emojis.warning} This command can only be used in a server!**`,
        noBanner: `**${emojis.emojis.warning} This server doesn't have a banner set!**`,
        banner: `'s Server Banner`,
        requestedBy: `Requested by`,
        errorFetching: `**${emojis.emojis.warning} An error occurred while fetching the avatar!**`,
        invalidUser: `**${emojis.emojis.warning} Invalid user provided!**`,
        type: `Type:`,
        accentColor: `Color:`,
        userBanner: `'s Banner`,
        global: `Global`,
        bannerTypes: {
            static: `Static (PNG)`,
            animated: `Animated (GIF)`,
        },
        qualityDownload: {
            sd: `Download SD`,
            hd: `Download HD`,
            uhd: `Download 4K`,
        },
    },

    // Shared / common strings
    common: {
        coins: `coins`,
        captchaFailed: `**${emojis.emojis.warning} Failed to generate captcha image. Please try again.**`,
        captchaPrompt: `${emojis.emojis.loading} Please type the letters shown in the image below within **{{seconds}} seconds**.`,
        captchaIncorrect: `**${emojis.emojis.warning} Incorrect captcha.**`,
        captchaTimeout: `**${emojis.emojis.warning} Verification timed out.**`,
        entered: `You entered`,
        expected: `Expected`,
        nothing: `nothing`,
        noReason: `No reason provided`,
        underDevelopment: `**${emojis.emojis.warning} This command is under development.**`,
    },

    economy: {
        balance: {
            title: `{{user}}'s Economic Profile`,
            wallet: `Wallet Balance`,
            bank: `Bank Balance`,
            total: `Total Net Worth`,
            transactions: `Recent Transactions`,
            noTransactions: `No recent transactions found.`,
            requestedBy: `Requested by`,
            cooldown: `Daily Reward`,
            ready: `Ready to claim!`,
            notReady: `Available in {{time}}`,
        },
        buttons: {
            refresh: `Refresh`,
            transactions: `Transactions`,
            back: `Back`,
            daily: `Claim Daily`,
        },
        transfer: {
            success: `Transfer successful.`,
            recipient: `Recipient`,
            received: `Received`,
            tax: `Tax (5%)`,
            totalSent: `Total sent`,
            insufficient: `You don't have enough coins!`,
            invalidAmount: `Invalid amount. Please enter a whole number greater than 0 (decimals are not allowed).`,
            selfTransfer: `Transfer failed: you cannot send coins to yourself.`,
            botTransfer: `Transfer failed: bot accounts cannot receive coins.`,
            accountTooNew: `Transfer blocked: your Discord account must be at least 30 days old.`,
            recipientTooNew: `Transfer blocked: recipient account must be at least 30 days old.`,
            insufficientBalance: `Transfer failed: insufficient balance.\nYour current balance: **{{balance}}** coins.`,
            captchaRequired: `Transfer verification required.`,
            captchaChannel: `Transfer failed: captcha verification must be done in a server text channel.`,
            captchaFailed: `Transfer failed: captcha image could not be generated right now. Please try again.`,
            captchaTimeout: `Transfer cancelled: captcha timed out.`,
            captchaIncorrect: `Transfer cancelled: captcha was incorrect.`,
            captchaHint: `Make sure to type only the 6 characters shown in the image.`,
            balanceChanged: `Transfer cancelled: your balance changed during verification.\nCurrent balance: **{{balance}}** coins.`,
            reason: `Reason: {{reason}}`,
            // DM notification
            dmGreetings: [
                `You have received an incoming transfer of {{amount}} Velvra coins from {{sender}}`,
                `Cha-ching! You just received {{amount}} Velvra coins from {{sender}}!`,
                `Good news! {{sender}} has sent you {{amount}} Velvra coins.`,
                `Transfer Alert! {{sender}} transferred {{amount}} Velvra coins to you.`,
            ],
            dmTransferType: `Transfer Type: None`,
            dmReason: `Reason`,
        },
        daily: {
            verification: `Daily Reward Verification`,
            alreadyClaimed: `You have already claimed your daily reward! Come back in **{{time}}**.`,
            success: `Daily reward claimed successfully!`,
            received: `You received **{{amount}}** coins.`,
            newBalance: `Your new balance: **{{balance}}** coins.`,
            cancelledIncorrect: `Claim cancelled: Incorrect captcha.`,
            cancelledTimeout: `Claim cancelled: Verification timed out.`,
        },
        reputation: {
            verification: `Reputation Verification`,
            cannotBot: `You cannot give reputation to bots.`,
            cannotSelf: `You cannot give reputation to yourself.`,
            alreadyGiven: `You have already given reputation recently! Come back in **{{time}}**.`,
            success: `You successfully gave a reputation point to **{{user}}**!\nThey now have **{{count}}** reputation.`,
            cancelledIncorrect: `Reputation cancelled: Incorrect captcha.`,
            cancelledTimeout: `Reputation cancelled: Verification timed out.`,
            // DM notification
            dmReceived: `You have received a reputation point from {{sender}}!`,
            dmTotal: `You now have {{count}} reputation point(s).`,
        },
    },

    giveaway: {
        verification: `Giveaway Action Verification`,
        verificationPrompt: `Please type the characters in the image to proceed with the **{{action}}** command.`,
        verificationFailed: `Verification failed.`,
        verificationTimeout: `Verification timed out.`,
        captchaFailed: `Failed to generate security captcha. Please try again.`,
        error: `An error occurred while executing the giveaway command.`,
        start: {
            invalidDuration: `Invalid duration format. Use: 1d, 2h, 15m, 30s`,
            embedTitle: `🎉 {{prize}}`,
            enterPrompt: `Click the 🎉 button below to enter!`,
            winners: `Winners`,
            host: `Host`,
            ends: `Ends`,
            enterButton: `Enter`,
            footer: `Giveaway`,
            success: `Giveaway started in {{channel}}!`,
        },
        end: {
            notFound: `Giveaway not found in this server.`,
            notRunning: `This giveaway is already ended or canceled.`,
            ended: `Giveaway Ended`,
            endedAnnouncement: `🎉 **Giveaway Ended!** Winner(s): {{winners}}`,
            noEntrants: `No one entered.`,
            none: `None`,
            success: `Giveaway successfully ended early.`,
        },
        reroll: {
            notFound: `Giveaway not found.`,
            notFinished: `Giveaway must be finished to reroll.`,
            announcement: `🔄 **Reroll!** New winner(s) for **{{prize}}**: {{winners}}`,
            noEntrants: `No valid entrants to pick from.`,
            success: `Giveaway rerolled.`,
        },
        remove: {
            notFound: `Giveaway not found.`,
            success: `Giveaway for **{{prize}}** removed from database.`,
        },
        list: {
            title: `Active Giveaways`,
            noActive: `There are no active giveaways in this server.`,
        },
        enter: {
            alreadyEnded: `This giveaway has already ended!`,
            alreadyEntered: `You have already entered this giveaway!`,
            success: `🎉 You have successfully entered the giveaway!`,
        },
    },

    server: {
        helpMENUtitle: `Velvra Help Menu`,
        helpMENUdesc: `Select a category below to explore commands.`,
        selectCATEGORY: `Select a category`,
        selectCOMMAND: `Select a command`,
        cmdNAME: `Command:`,
        noDescription: `No description provided.`,
        usage: `Usage`,
        category: `Category`,
        type: `Type`,
        cooldown: `Cooldown`,
        none: `None`,
        userPerms: `User Permissions`,
        botPerms: `Bot Permissions`,
        aliases: `Aliases`,
        info: `Total: {{slash}} Slash | {{prefix}} Prefix`,
        slash: `Slash`,
        prefix: `Prefix`,
        push: `Push`,
        and: `&`,
        unknown: `Unknown`,
        commandNotFOUND: `Command \`{{command}}\` not found.`,
        serverINFO: `Server Information`,
        serverName: `Server Name`,
        serverID: `Server ID`,
        owner: `Owner`,
        memberCount: `Members`,
        creationDate: `Created At`,
        boostLevel: `Boost Status`,
        boosts: `Level {{level}} ({{boostsCount}} Boosts)`,
        totalRoles: `Roles`,
        totalChannels: `Channels`,
        region: `Region`,
        requestedBy: `Requested by`,
        onlyInServer: `This command can only be used in a server!`,
    },

    clear: {
        noTextChannel: `This command can only be used in a text channel.`,
        title: `Clear Summary`,
        channel: `Channel`,
        requested: `Requested`,
        filtered: `Filtered`,
        deleted: `Deleted`,
        bulk: `Bulk`,
        singleOld: `Single (old)`,
        errors: `Errors`,
        reason: `Reason: {{reason}}`,
        deletedNotice: `Deleted {{count}} message(s).`,
        noReason: `No reason provided`,
    },

    warn: {
        guildRequired: `Guild context required.`,
        userNotFound: `User not found in guild.`,
        cannotHigher: `You cannot warn this user due to role hierarchy.`,
        title: `User Warned`,
        user: `User`,
        infractionId: `Infraction ID`,
        activeWarnings: `Active Warnings`,
        reason: `Reason`,
        moderator: `Moderator`,
        dmNotice: `You have received a warning in **{{guild}}**. Reason: {{reason}} (ID: {{id}})`,
        noReason: `No reason provided`,
    },

    warnings: {
        guildRequired: `Guild context required.`,
        title: `Warnings for {{user}}`,
        noWarningsActive: `No active warnings for this user.`,
        noWarningsAll: `No warnings found (including inactive).`,
        active: `Active`,
        inactive: `Inactive`,
        removed: `Removed`,
        totalReturned: `Total Returned`,
        includingInactive: `Including Inactive`,
        yes: `Yes`,
        no: `No`,
        requestedBy: `Requested by {{user}}`,
    },

    warnRemove: {
        title: `Warning Deactivated`,
        notFound: `Warning not found.`,
        alreadyInactive: `Warning is already inactive.`,
        remainingActive: `Remaining Active`,
        userId: `User ID`,
        removalReason: `Removal Reason`,
        noReason: `No reason provided`,
    },

    role: {
        onlyInServer: `This command can only be used in a server!`,
        mustSpecifyRole: `You must specify a role.`,
        userNotFound: `User not found in this guild.`,
        alreadyHasRole: `This user already has the specified role.`,
        doesNotHaveRole: `This user does not have the specified role.`,
        giveSuccess: `Successfully gave role {{role}} to {{user}}. Reason: {{reason}}`,
        removeSuccess: `Successfully removed role {{role}} from {{user}}. Reason: {{reason}}`,
        giveFail: `Failed to give the role. Do I have the correct permissions? Make sure my role is higher than the role you're trying to assign.\n-# If the problem persists, please contact support.`,
        removeFail: `Failed to remove the role. Do I have the correct permissions? Make sure my role is higher than the role you're trying to remove.\n-# If the problem persists, please contact support.`,
        giveBotSuccess: `Successfully gave role {{role}} to {{success}} bots. Failed to give role to {{fail}} bots. Reason: {{reason}}`,
        removeBotSuccess: `Successfully removed role {{role}} from {{success}} bots. Failed to remove role from {{fail}} bots. Reason: {{reason}}`,
        giveAllSuccess: `Successfully gave role {{role}} to {{success}} members. Failed to give role to {{fail}} members. Reason: {{reason}}`,
        removeAllSuccess: `Successfully removed role {{role}} from {{success}} members. Failed to remove role from {{fail}} members. Reason: {{reason}}`,
        mustSpecifyTarget: `You must specify a user, or choose to apply to all bots or all members.`,
        noReason: `No reason provided`,
    },

    slowmode: {
        noTextChannel: `Target channel must be a text-capable channel.`,
        invalidDuration: `Invalid duration format. Use examples like 10s, 5m, 2h, 1d, or 0 to disable.`,
        noChildChannels: `No child text channels found in that category.`,
        title: `⏱ Slowmode Updated`,
        newRateLimit: `New Rate Limit`,
        channelsUpdated: `Channels Updated`,
        failed: `Failed`,
        errors: `Errors`,
        reason: `Reason: {{reason}}`,
        appliedToCategory: `Applied to category: **{{name}}**`,
        channel: `Channel`,
        noReason: `No reason provided`,
    },

    nickname: {
        userNotFound: `User not found in this guild.`,
        cannotSelf: `You cannot change your own nickname with this command.`,
        cannotBot: `You cannot change the bot's nickname.`,
        cannotHigher: `You cannot manage a member with an equal or higher role than yours.`,
        cannotModerate: `I cannot manage this user's nickname. They might have a higher role than me.`,
        successReset: `Successfully reset {{user}}'s nickname.`,
        successSet: `Successfully changed {{user}}'s nickname to **{{nickname}}**.`,
        error: `Failed to change {{user}}'s nickname: {{error}}`,
    },

    disconnect: {
        no_reason: `No reason provided`,
        not_found: `User not found.`,
        not_in_voice: `This user is not in a voice channel.`,
        owner: `You cannot disconnect the server owner.`,
        higher_user: `You cannot disconnect a member with an equal or higher role than yours.`,
        higher_bot: `I cannot disconnect this user. Their role is higher than mine.`,
        user_title: `User Disconnected`,
        user_desc: `**{user}** has been disconnected from voice.`,
        channel: `Channel`,
        moderator: `Moderator`,
        reason: `Reason`,
        failed: `Failed to disconnect: {error}`,
        invalid_channel: `This channel is not a voice channel.`,
        empty_channel: `No members in this voice channel.`,
        mass_title: `Mass Disconnect`,
        mass_desc: `All users disconnected from **{channel}**.`,
        success: `Disconnected`,
        no_premium: `**${emojis.emojis.warning} This feature requires a premium subscription. Please upgrade to use mass disconnect.**`,
    },

    addemoji: {
        invalidFileType: `Invalid file type. Allowed: {types}`,
        fileTooLarge: `File too large. Maximum: {max}KB`,
        invalidSource: `Invalid source. Provide a URL or an existing emoji.`,
        urlInvalidType: `URL points to an invalid file type. Allowed: {types}`,
        fileTooBigRemote: `Remote file too large. Maximum: {max}KB`,
        mustProvideSource: `You must provide a source (URL, emoji, or file attachment).`,
        emojiSuccessTitle: `Emoji Added`,
        emojiSuccessDesc: `Added {emoji} as **{name}**`,
        emojiFail: `Failed to add emoji: {error}`,
        missingTags: `You must provide valid Unicode emoji tags.`,
        mustProvideSticker: `You must provide a source (URL or file attachment) for the sticker.`,
        stickerSuccessTitle: `Sticker Added`,
        stickerSuccessDesc: `Added sticker **{name}**`,
        stickerFail: `Failed to add sticker: {error}`,
    },

    leveling: {
        underDevelopment: `This command is under development.`,
        quest: {
            authorTitle: `{{user}}'s Daily Quests`,
            title: `Your Daily Quests`,
            description: `Complete your daily activities to earn **XP** and **Coins**!\nKeep it up and reach the top of the leaderboard! 💪`,
            messagesTitle: `Messages`,
            messagesGoal: `Goal`,
            messagesReward: `Reward`,
            messagesProgress: `Progress`,
            voiceTitle: `Voice Activity`,
            voiceGoal: `Goal`,
            voiceReward: `Reward`,
            voiceProgress: `Progress`,
            footer: `Velvra Quests`,
        },
    },

    ping: {
        pinging: `Pinging...`,
        networkError: `Network Error`,
        excellent: `Excellent`,
        good: `Good`,
        high: `High`,
        severeLag: `Severe Lag`,
        pong: `🏓 Pong!`,
        wsPingTitle: `📡 Websocket Ping`,
        msgLatencyTitle: `⏱️ Message Latency`,
    },

    backup: {
        error: `An unexpected error occurred while processing your backup command. Please try again later.`,
        create: {
            title: `Backup Successfully Created`,
            description: `Your server backup has been created and is ready for restoration.`,
            backupId: `Backup ID`,
            rolesCaptured: `Roles Captured`,
            channelsCaptured: `Channels Captured`,
            bansCaptured: `Bans Captured`,
            archiveSize: `Archive Size`,
            createdAt: `Created At`,
            createdBy: `Backup created by {{user}}`,
            failed: `An error occurred while creating your server backup. Please try again later.`,
        },
        info: {
            title: `Backup Information`,
            crossGuild: `This backup exists but belongs to a different server.`,
            notFound: `The specified backup ID could not be located.`,
            rolesStored: `Roles Stored`,
            channelsStored: `Channels Stored`,
            bansStored: `Bans Stored`,
            createdBy: `Created By`,
            created: `Created`,
        },
        list: {
            title: `Server Backups`,
            noBackups: `This server doesn't have any backups yet. Use \`/backup create\` to create your first backup!`,
            gettingStarted: `Creating regular backups helps protect your server configuration.`,
            description: `Here are your most recent server backups:`,
            available: `Available Backups`,
        },
        load: {
            confirmRequired: `You must set \`confirm\` to \`true\` to proceed with backup restoration.`,
            notFound: `The specified backup ID could not be located.`,
            unavailable: `This backup cannot be restored right now. Status: {{status}}`,
            empty: `This backup contains no restorable content.`,
            crossGuildWarning: `This backup was created in a different server. Some elements may not restore perfectly.`,
            title: `Backup Restoration`,
            instructions: `Select the components you want to restore using the dropdown menu below.`,
            selectPlaceholder: `Select sections to restore (optional)`,
            continueBtn: `Continue`,
            cancelBtn: `Cancel`,
            canceled: `The backup restoration process has been canceled.`,
            purgeChannels: `Purging existing channels & categories...`,
            purgeRoles: `Purging existing roles...`,
            completedTitle: `Restoration Completed Successfully`,
            restoredComponents: `Restored Components`,
            resultsSummary: `Results Summary`,
            purgeSummary: `Purge Summary`,
            issues: `Issues Encountered`,
            noIssues: `ll operations completed without issues!`,
            failed: `**Restoration Failed**\nAn unexpected error occurred during the restoration process. Please try again or contact an administrator for assistance.`,
            commandChannelContext: `Channel Context`,
            commandChannelPreserved: `🛟 Command channel preserved to allow interaction responses.`,
            commandChannelNotPreserved: `Command channel was not preserved.`,
        },
        cancel: {
            noActive: `There are no backup creation processes currently running.`,
            success: `Backup creation for \`{{id}}\` has been canceled.`,
        },
        delete: {
            notFound: `The specified backup ID could not be located.`,
            alreadyDeleted: `This backup has already been deleted.`,
            success: `Backup \`{{id}}\` has been deleted.`,
        },
    },
};
