const emojis = require('./../emojis');

module.exports = {
    test: `これは日本語のテスト文字列です`,
    timeout: {
        userNotFound: `**${emojis.emojis.incorrect} このサーバーにユーザーが見つかりません。**`,
        invalidDuration: `**${emojis.emojis.warning} 無効な期間形式です。10m、1h、1dなどの形式を使用してください。**`,
        durationExceed: `**${emojis.emojis.warning} 期間は28日を超えることができません。**`,
        success: {
            set: `**${emojis.emojis.correct} {{user}}を{{duration}}の間タイムアウトしました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
            remove: `**${emojis.emojis.correct} {{user}}のタイムアウトを解除しました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} ユーザーのタイムアウトに失敗しました。正しい権限がありますか？自分のロールがユーザーのロールより上であることを確認してください。\n-# 問題が解決しない場合は、サポートにお問い合わせください。**`,
        cannotSelf: `**${emojis.emojis.warning} 自分自身をタイムアウトすることはできません。**`,
        cannotBot: `**${emojis.emojis.warning} 私をタイムアウトすることはできません。**`,
        cannotHigher: `**${emojis.emojis.warning} 同等以上のロールを持つメンバーをタイムアウトすることはできません。**`,
        cannotModerate: `**${emojis.emojis.warning} このユーザーをタイムアウトできません。より高いロールを持っているか、管理者権限を持っている可能性があります。**`,
        invalidAction: `**${emojis.emojis.incorrect} 無効なアクションです。'set'または'remove'を使用してください。**`,
    },
    ban: {
        userNotFound: `**${emojis.emojis.incorrect} このサーバーにユーザーが見つかりません。**`,
        success: {
            give: `**${emojis.emojis.correct} {{user}}をBANしました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
            remove: `**${emojis.emojis.correct} {{user}}のBANを解除しました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} ユーザーのBAN/BAN解除に失敗しました。正しい権限がありますか？自分のロールがユーザーのロールより上であることを確認してください。\n-# 問題が解決しない場合は、サポートにお問い合わせください。**`,
        cannotSelf: `**${emojis.emojis.warning} 自分自身をBANすることはできません。**`,
        cannotBot: `**${emojis.emojis.warning} なぜ？詳しくはサポートサーバーにお問い合わせください。**`,
        cannotHigher: `**${emojis.emojis.warning} 同等以上のロールを持つメンバーをBANすることはできません。**`,
        cannotModerate: `**${emojis.emojis.warning} このユーザーをBANできません。より高いロールを持っているか、管理者権限を持っている可能性があります。**`,
        invalidAction: `**${emojis.emojis.incorrect} 無効なアクションです。'give'または'remove'を使用してください。**`,
        alreadyBanned: `**${emojis.emojis.warning} このユーザーは既にBANされています。**`,
    },
    kick: {
        userNotFound: `**${emojis.emojis.incorrect} このサーバーにユーザーが見つかりません。**`,
        kicked: `**${emojis.emojis.correct} {{user}}をキックしました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} ユーザーのキックに失敗しました。正しい権限がありますか？自分のロールがユーザーのロールより上であることを確認してください。\n-# 問題が解決しない場合は、サポートにお問い合わせください。**`,
        cannotSelf: `**${emojis.emojis.warning} 自分自身をキックすることはできません。**`,
        cannotBot: `**${emojis.emojis.warning} 私をキックすることはできません。**`,
        cannotHigher: `**${emojis.emojis.warning} 同等以上のロールを持つメンバーをキックすることはできません。**`,
        botCannotHigher: `**${emojis.emojis.warning} 同等以上のロールを持つメンバーをキックできません。**`,
        cannotModerate: `**${emojis.emojis.warning} このユーザーをキックできません。より高いロールを持っているか、管理者権限を持っている可能性があります。**`,
    },
    unban: {
        userNotFound: `**${emojis.emojis.incorrect} ユーザーIDが指定されていません。**`,
        userNotBanned: `**${emojis.emojis.warning} このユーザーはBANされていません。**`,
        unbanned: `**${emojis.emojis.correct} {{user}}のBANを解除しました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} ユーザーのBAN解除に失敗しました。エラー: {{error}}**`,
    },
    lock: {
        channelNotFound: `**${emojis.emojis.incorrect} チャンネルが見つかりません。**`,
        locked: `**${emojis.emojis.correct} {{channel}}をロックしました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
        alreadyLocked: `**${emojis.emojis.warning} このチャンネルは既にロックされています。**`,
        error: `**${emojis.emojis.incorrect} チャンネルのロックに失敗しました。正しい権限がありますか？\n-# 問題が解決しない場合は、サポートにお問い合わせください。**`,
        cannotLock: `**${emojis.emojis.warning} このチャンネルをロックできません。正しい権限がありますか？**`,
    },
    unlock: {
        channelNotFound: `**${emojis.emojis.incorrect} チャンネルが見つかりません。**`,
        unlocked: `**${emojis.emojis.correct} {{channel}}のロックを解除しました。 ${emojis.emojis.reason} 理由: {{reason}}**`,
        notLocked: `**${emojis.emojis.warning} このチャンネルはロックされていません。**`,
        error: `**${emojis.emojis.incorrect} チャンネルのロック解除に失敗しました。正しい権限がありますか？\n-# 問題が解決しない場合は、サポートにお問い合わせください。**`,
        cannotUnlock: `**${emojis.emojis.warning} このチャンネルのロックを解除できません。正しい権限がありますか？**`,
    },

    avatar: {
        onlyInServer: `**${emojis.emojis.warning} このコマンドはサーバー内でのみ使用できます！**`,
        noIcon: `**${emojis.emojis.warning} このサーバーにはアイコンが設定されていません！**`,
        noAvatar: `**${emojis.emojis.warning} ユーザー{{user}}にはアバターがありません！**`,
        avatar: `のアバター`,
        requestedBy: `リクエスト者`,
        errorFetching: `**${emojis.emojis.warning} アバターの取得中にエラーが発生しました！**`,
        invalidUser: `**${emojis.emojis.warning} 無効なユーザーです！**`,
        type: `タイプ:`,
        icon: `のサーバーアイコン`,
        avatarTypes: {
            static: `静止画 (PNG)`,
            animated: `アニメーション (GIF)`,
        },
        qualityDownload: {
            sd: `SDをダウンロード`,
            hd: `HDをダウンロード`,
            uhd: `4Kをダウンロード`,
        },
    },

    banner: {
        onlyInServer: `**${emojis.emojis.warning} このコマンドはサーバー内でのみ使用できます！**`,
        noBanner: `**${emojis.emojis.warning} このサーバーにはバナーが設定されていません！**`,
        banner: `のサーバーバナー`,
        requestedBy: `リクエスト者`,
        errorFetching: `**${emojis.emojis.warning} 画像の取得中にエラーが発生しました！**`,
        invalidUser: `**${emojis.emojis.warning} 無効なユーザーです！**`,
        type: `タイプ:`,
        accentColor: `カラー:`,
        userBanner: `のバナー`,
        global: `グローバル`,
        bannerTypes: {
            static: `静止画 (PNG)`,
            animated: `アニメーション (GIF)`,
        },
        qualityDownload: {
            sd: `SDをダウンロード`,
            hd: `HDをダウンロード`,
            uhd: `4Kをダウンロード`,
        },
    },

    // 共通文字列
    common: {
        coins: `コイン`,
        captchaFailed: `**${emojis.emojis.warning} キャプチャ画像の生成に失敗しました。もう一度お試しください。**`,
        captchaPrompt: `${emojis.emojis.loading} 以下の画像に表示されている文字を**{{seconds}}秒**以内に入力してください。`,
        captchaIncorrect: `**${emojis.emojis.warning} キャプチャが正しくありません。**`,
        captchaTimeout: `**${emojis.emojis.warning} 認証がタイムアウトしました。**`,
        entered: `入力した内容`,
        expected: `期待される内容`,
        nothing: `なし`,
        noReason: `理由が指定されていません`,
        underDevelopment: `**${emojis.emojis.warning} このコマンドは開発中です。**`,
    },

    economy: {
        balance: {
            title: `{{user}}の経済プロフィール`,
            wallet: `ウォレット残高`,
            bank: `銀行残高`,
            total: `総資産`,
            transactions: `最近の取引`,
            noTransactions: `最近の取引はありません。`,
            requestedBy: `リクエスト者`,
            cooldown: `デイリー報酬`,
            ready: `受け取り可能！`,
            notReady: `{{time}}後に利用可能`,
        },
        buttons: {
            refresh: `更新`,
            transactions: `取引履歴`,
            back: `戻る`,
            daily: `デイリーを受け取る`,
        },
        transfer: {
            success: `送金が完了しました。`,
            recipient: `受取人`,
            received: `受取済み`,
            tax: `税金 (5%)`,
            totalSent: `送金合計`,
            insufficient: `コインが不足しています！`,
            invalidAmount: `無効な金額です。0より大きい整数を入力してください（小数は使用できません）。`,
            selfTransfer: `送金失敗: 自分自身にコインを送ることはできません。`,
            botTransfer: `送金失敗: ボットアカウントはコインを受け取れません。`,
            accountTooNew: `送金ブロック: Discordアカウントは30日以上経過している必要があります。`,
            recipientTooNew: `送金ブロック: 受取人のアカウントは30日以上経過している必要があります。`,
            insufficientBalance: `送金失敗: 残高不足です。\n現在の残高: **{{balance}}** コイン。`,
            captchaRequired: `送金の認証が必要です。`,
            captchaChannel: `送金失敗: キャプチャ認証はサーバーのテキストチャンネルで行う必要があります。`,
            captchaFailed: `送金失敗: キャプチャ画像を生成できませんでした。もう一度お試しください。`,
            captchaTimeout: `送金キャンセル: キャプチャがタイムアウトしました。`,
            captchaIncorrect: `送金キャンセル: キャプチャが正しくありません。`,
            captchaHint: `画像に表示されている6文字のみを入力してください。`,
            balanceChanged: `送金キャンセル: 認証中に残高が変更されました。\n現在の残高: **{{balance}}** コイン。`,
            reason: `理由: {{reason}}`,
            // DM通知
            dmGreetings: [
                `{{sender}}から{{amount}} Velvraコインの送金を受け取りました`,
                `チャリン！{{sender}}から{{amount}} Velvraコインを受け取りました！`,
                `朗報です！{{sender}}があなたに{{amount}} Velvraコインを送りました。`,
                `送金通知！{{sender}}が{{amount}} Velvraコインを送金しました。`,
            ],
            dmTransferType: `送金タイプ: なし`,
            dmReason: `理由`,
        },
        daily: {
            verification: `デイリー報酬の認証`,
            alreadyClaimed: `デイリー報酬は既に受け取り済みです！**{{time}}**後にまたお越しください。`,
            success: `デイリー報酬を受け取りました！`,
            received: `**{{amount}}** コインを獲得しました。`,
            newBalance: `新しい残高: **{{balance}}** コイン。`,
            cancelledIncorrect: `受け取りキャンセル: キャプチャが正しくありません。`,
            cancelledTimeout: `受け取りキャンセル: 認証がタイムアウトしました。`,
        },
        reputation: {
            verification: `レピュテーション認証`,
            cannotBot: `ボットにレピュテーションを与えることはできません。`,
            cannotSelf: `自分自身にレピュテーションを与えることはできません。`,
            alreadyGiven: `最近レピュテーションを与えました！**{{time}}**後にまたお越しください。`,
            success: `**{{user}}**にレピュテーションポイントを与えました！\n現在**{{count}}**レピュテーションです。`,
            cancelledIncorrect: `レピュテーションキャンセル: キャプチャが正しくありません。`,
            cancelledTimeout: `レピュテーションキャンセル: 認証がタイムアウトしました。`,
            // DM通知
            dmReceived: `{{sender}}からレピュテーションポイントを受け取りました！`,
            dmTotal: `現在のレピュテーション: {{count}}ポイント。`,
        },
    },

    giveaway: {
        verification: `ギブアウェイアクション認証`,
        verificationPrompt: `**{{action}}**コマンドを続行するには、画像の文字を入力してください。`,
        verificationFailed: `認証に失敗しました。`,
        verificationTimeout: `認証がタイムアウトしました。`,
        captchaFailed: `セキュリティキャプチャの生成に失敗しました。もう一度お試しください。`,
        error: `ギブアウェイコマンドの実行中にエラーが発生しました。`,
        start: {
            invalidDuration: `無効な期間形式です。1d、2h、15m、30sを使用してください`,
            embedTitle: `🎉 {{prize}}`,
            enterPrompt: `下の🎉ボタンをクリックして参加しましょう！`,
            winners: `当選者`,
            host: `主催者`,
            ends: `終了`,
            enterButton: `参加`,
            footer: `ギブアウェイ`,
            success: `{{channel}}でギブアウェイを開始しました！`,
        },
        end: {
            notFound: `このサーバーにギブアウェイが見つかりません。`,
            notRunning: `このギブアウェイは既に終了またはキャンセルされています。`,
            ended: `ギブアウェイ終了`,
            endedAnnouncement: `🎉 **ギブアウェイ終了！** 当選者: {{winners}}`,
            noEntrants: `参加者がいません。`,
            none: `なし`,
            success: `ギブアウェイを早期終了しました。`,
        },
        reroll: {
            notFound: `ギブアウェイが見つかりません。`,
            notFinished: `再抽選するにはギブアウェイが終了している必要があります。`,
            announcement: `🔄 **再抽選！** **{{prize}}**の新しい当選者: {{winners}}`,
            noEntrants: `選出できる有効な参加者がいません。`,
            success: `ギブアウェイを再抽選しました。`,
        },
        remove: {
            notFound: `ギブアウェイが見つかりません。`,
            success: `**{{prize}}**のギブアウェイをデータベースから削除しました。`,
        },
        list: {
            title: `開催中のギブアウェイ`,
            noActive: `このサーバーには開催中のギブアウェイがありません。`,
        },
        enter: {
            alreadyEnded: `このギブアウェイは既に終了しています！`,
            alreadyEntered: `既にこのギブアウェイに参加しています！`,
            success: `🎉 ギブアウェイへの参加が完了しました！`,
        },
    },

    server: {
        helpMENUtitle: `Velvra ヘルプメニュー`,
        helpMENUdesc: `下のカテゴリを選択してコマンドを探索しましょう。`,
        selectCATEGORY: `カテゴリを選択`,
        selectCOMMAND: `コマンドを選択`,
        cmdNAME: `コマンド:`,
        noDescription: `説明はありません。`,
        usage: `使い方`,
        category: `カテゴリ`,
        type: `タイプ`,
        cooldown: `クールダウン`,
        none: `なし`,
        userPerms: `ユーザー権限`,
        botPerms: `ボット権限`,
        aliases: `エイリアス`,
        info: `合計: {{slash}} スラッシュ | {{prefix}} プレフィックス`,
        slash: `スラッシュ`,
        prefix: `プレフィックス`,
        push: `プッシュ`,
        and: `&`,
        unknown: `不明`,
        commandNotFOUND: `コマンド \`{{command}}\` が見つかりません。`,
        serverINFO: `サーバー情報`,
        serverName: `サーバー名`,
        serverID: `サーバーID`,
        owner: `オーナー`,
        memberCount: `メンバー数`,
        creationDate: `作成日`,
        boostLevel: `ブーストステータス`,
        boosts: `レベル {{level}} ({{boostsCount}} ブースト)`,
        totalRoles: `ロール`,
        totalChannels: `チャンネル`,
        region: `地域`,
        requestedBy: `リクエスト者`,
        onlyInServer: `このコマンドはサーバー内でのみ使用できます！`,
    },

    clear: {
        noTextChannel: `このコマンドはテキストチャンネルでのみ使用できます。`,
        title: `削除サマリー`,
        channel: `チャンネル`,
        requested: `リクエスト数`,
        filtered: `フィルター済み`,
        deleted: `削除済み`,
        bulk: `一括`,
        singleOld: `単体 (古い)`,
        errors: `エラー`,
        reason: `理由: {{reason}}`,
        deletedNotice: `{{count}}件のメッセージを削除しました。`,
        noReason: `理由が指定されていません`,
    },

    warn: {
        guildRequired: `サーバーコンテキストが必要です。`,
        userNotFound: `サーバーにユーザーが見つかりません。`,
        cannotHigher: `ロール階層により、このユーザーに警告することはできません。`,
        title: `ユーザーに警告`,
        user: `ユーザー`,
        infractionId: `違反ID`,
        activeWarnings: `有効な警告`,
        reason: `理由`,
        moderator: `モデレーター`,
        dmNotice: `**{{guild}}**で警告を受けました。理由: {{reason}} (ID: {{id}})`,
        noReason: `理由が指定されていません`,
    },

    warnings: {
        guildRequired: `サーバーコンテキストが必要です。`,
        title: `{{user}}の警告一覧`,
        noWarningsActive: `このユーザーには有効な警告がありません。`,
        noWarningsAll: `警告が見つかりません（無効な警告を含む）。`,
        active: `有効`,
        inactive: `無効`,
        removed: `削除済み`,
        totalReturned: `返された合計`,
        includingInactive: `無効な警告を含む`,
        yes: `はい`,
        no: `いいえ`,
        requestedBy: `リクエスト者 {{user}}`,
    },

    warnRemove: {
        title: `警告を無効化`,
        notFound: `警告が見つかりません。`,
        alreadyInactive: `この警告は既に無効です。`,
        remainingActive: `残りの有効な警告`,
        userId: `ユーザーID`,
        removalReason: `削除理由`,
        noReason: `理由が指定されていません`,
    },

    role: {
        onlyInServer: `このコマンドはサーバー内でのみ使用できます！`,
        mustSpecifyRole: `ロールを指定してください。`,
        userNotFound: `このサーバーにユーザーが見つかりません。`,
        alreadyHasRole: `このユーザーは既に指定されたロールを持っています。`,
        doesNotHaveRole: `このユーザーは指定されたロールを持っていません。`,
        giveSuccess: `{{user}}にロール{{role}}を付与しました。理由: {{reason}}`,
        removeSuccess: `{{user}}からロール{{role}}を削除しました。理由: {{reason}}`,
        giveFail: `ロールの付与に失敗しました。正しい権限がありますか？付与するロールより上のロールを持っていることを確認してください。\n-# 問題が解決しない場合は、サポートにお問い合わせください。`,
        removeFail: `ロールの削除に失敗しました。正しい権限がありますか？削除するロールより上のロールを持っていることを確認してください。\n-# 問題が解決しない場合は、サポートにお問い合わせください。`,
        giveBotSuccess: `{{success}}台のボットにロール{{role}}を付与しました。{{fail}}台のボットへの付与に失敗しました。理由: {{reason}}`,
        removeBotSuccess: `{{success}}台のボットからロール{{role}}を削除しました。{{fail}}台のボットからの削除に失敗しました。理由: {{reason}}`,
        giveAllSuccess: `{{success}}人のメンバーにロール{{role}}を付与しました。{{fail}}人のメンバーへの付与に失敗しました。理由: {{reason}}`,
        removeAllSuccess: `{{success}}人のメンバーからロール{{role}}を削除しました。{{fail}}人のメンバーからの削除に失敗しました。理由: {{reason}}`,
        mustSpecifyTarget: `ユーザーを指定するか、すべてのボットまたはすべてのメンバーに適用するかを選択してください。`,
        noReason: `理由が指定されていません`,
    },

    slowmode: {
        noTextChannel: `対象チャンネルはテキストチャンネルである必要があります。`,
        invalidDuration: `無効な期間形式です。10s、5m、2h、1d、または0（無効化）を使用してください。`,
        noChildChannels: `このカテゴリにテキストチャンネルが見つかりません。`,
        title: `⏱ 低速モード更新`,
        newRateLimit: `新しいレート制限`,
        channelsUpdated: `更新されたチャンネル`,
        failed: `失敗`,
        errors: `エラー`,
        reason: `理由: {{reason}}`,
        appliedToCategory: `カテゴリに適用: **{{name}}**`,
        channel: `チャンネル`,
        noReason: `理由が指定されていません`,
    },

    nickname: {
        userNotFound: `このサーバーにユーザーが見つかりません。`,
        cannotSelf: `このコマンドで自分のニックネームを変更することはできません。`,
        cannotBot: `ボットのニックネームを変更することはできません。`,
        cannotHigher: `同等以上のロールを持つメンバーを管理することはできません。`,
        cannotModerate: `このユーザーのニックネームを管理できません。より高いロールを持っている可能性があります。`,
        successReset: `{{user}}のニックネームをリセットしました。`,
        successSet: `{{user}}のニックネームを**{{nickname}}**に変更しました。`,
        error: `{{user}}のニックネーム変更に失敗しました: {{error}}`,
    },

    disconnect: {
        no_reason: `理由が指定されていません`,
        not_found: `ユーザーが見つかりません。`,
        not_in_voice: `このユーザーはボイスチャンネルにいません。`,
        owner: `サーバーオーナーを切断することはできません。`,
        higher_user: `同等以上のロールを持つメンバーを切断することはできません。`,
        higher_bot: `このユーザーを切断できません。ロールが私より上位です。`,
        user_title: `ユーザーを切断`,
        user_desc: `**{user}**をボイスチャンネルから切断しました。`,
        channel: `チャンネル`,
        moderator: `モデレーター`,
        reason: `理由`,
        failed: `切断に失敗しました: {error}`,
        invalid_channel: `このチャンネルはボイスチャンネルではありません。`,
        empty_channel: `このボイスチャンネルにメンバーがいません。`,
        mass_title: `一括切断`,
        mass_desc: `**{channel}**からすべてのユーザーを切断しました。`,
        success: `切断完了`,
        no_premium: `**${emojis.emojis.warning} この機能はプレミアムサブスクリプションが必要です。一括切断を使用するにはアップグレードしてください。**`,
    },

    addemoji: {
        invalidFileType: `無効なファイル形式です。許可: {types}`,
        fileTooLarge: `ファイルが大きすぎます。最大: {max}KB`,
        invalidSource: `無効なソースです。URLまたは既存の絵文字を指定してください。`,
        urlInvalidType: `URLが無効なファイル形式を指しています。許可: {types}`,
        fileTooBigRemote: `リモートファイルが大きすぎます。最大: {max}KB`,
        mustProvideSource: `ソースを指定してください（URL、絵文字、またはファイル添付）。`,
        emojiSuccessTitle: `絵文字を追加`,
        emojiSuccessDesc: `{emoji}を**{name}**として追加しました`,
        emojiFail: `絵文字の追加に失敗しました: {error}`,
        missingTags: `有効なUnicode絵文字タグを指定してください。`,
        mustProvideSticker: `スタンプのソースを指定してください（URLまたはファイル添付）。`,
        stickerSuccessTitle: `スタンプを追加`,
        stickerSuccessDesc: `スタンプ**{name}**を追加しました`,
        stickerFail: `スタンプの追加に失敗しました: {error}`,
    },

    leveling: {
        underDevelopment: `このコマンドは開発中です。`,
        quest: {
            authorTitle: `{{user}}のデイリークエスト`,
            title: `あなたのデイリークエスト`,
            description: `デイリーアクティビティを完了して**XP**と**コイン**を獲得しましょう！\nリーダーボードのトップを目指そう！ 💪`,
            messagesTitle: `メッセージ`,
            messagesGoal: `目標`,
            messagesReward: `報酬`,
            messagesProgress: `進捗`,
            voiceTitle: `ボイスアクティビティ`,
            voiceGoal: `目標`,
            voiceReward: `報酬`,
            voiceProgress: `進捗`,
            footer: `Velvra クエスト`,
        },
    },

    ping: {
        pinging: `通信中...`,
        networkError: `ネットワークエラー`,
        excellent: `優秀`,
        good: `良好`,
        high: `高い`,
        severeLag: `深刻な遅延`,
        pong: `🏓 ポン！`,
        wsPingTitle: `📡 WebSocket Ping`,
        msgLatencyTitle: `⏱️ メッセージの遅延`,
    },

    backup: {
        error: `バックアップコマンドの処理中に予期しないエラーが発生しました。後でもう一度お試しください。`,
        create: {
            title: `バックアップ作成完了`,
            description: `サーバーのバックアップが作成され、復元の準備ができました。`,
            backupId: `バックアップID`,
            rolesCaptured: `保存されたロール`,
            channelsCaptured: `保存されたチャンネル`,
            bansCaptured: `保存されたBAN`,
            archiveSize: `アーカイブサイズ`,
            createdAt: `作成日時`,
            createdBy: `{{user}}がバックアップを作成しました`,
            failed: `サーバーバックアップの作成中にエラーが発生しました。後でもう一度お試しください。`,
        },
        info: {
            title: `バックアップ情報`,
            crossGuild: `このバックアップは存在しますが、別のサーバーに属しています。`,
            notFound: `指定されたバックアップIDが見つかりません。`,
            rolesStored: `保存されたロール`,
            channelsStored: `保存されたチャンネル`,
            bansStored: `保存されたBAN`,
            createdBy: `作成者`,
            created: `作成日`,
        },
        list: {
            title: `サーバーバックアップ`,
            noBackups: `このサーバーにはまだバックアップがありません。\`/backup create\`を使用して最初のバックアップを作成しましょう！`,
            gettingStarted: `定期的なバックアップ作成はサーバー設定の保護に役立ちます。`,
            description: `最新のサーバーバックアップ:`,
            available: `利用可能なバックアップ`,
        },
        load: {
            confirmRequired: `バックアップの復元を続行するには、\`confirm\`を\`true\`に設定してください。`,
            notFound: `指定されたバックアップIDが見つかりません。`,
            unavailable: `このバックアップは現在復元できません。ステータス: {{status}}`,
            empty: `このバックアップには復元可能なコンテンツがありません。`,
            crossGuildWarning: `このバックアップは別のサーバーで作成されました。一部の要素が完全に復元されない場合があります。`,
            title: `バックアップ復元`,
            instructions: `下のドロップダウンメニューから復元するコンポーネントを選択してください。`,
            selectPlaceholder: `復元するセクションを選択（任意）`,
            continueBtn: `続行`,
            cancelBtn: `キャンセル`,
            canceled: `バックアップの復元プロセスがキャンセルされました。`,
            purgeChannels: `既存のチャンネルとカテゴリを削除中...`,
            purgeRoles: `既存のロールを削除中...`,
            completedTitle: `復元が正常に完了しました`,
            restoredComponents: `復元されたコンポーネント`,
            resultsSummary: `結果サマリー`,
            purgeSummary: `削除サマリー`,
            issues: `発生した問題`,
            noIssues: `すべての操作が問題なく完了しました！`,
            failed: `**復元に失敗しました**\n復元プロセス中に予期しないエラーが発生しました。もう一度お試しいただくか、管理者にお問い合わせください。`,
            commandChannelContext: `チャンネルコンテキスト`,
            commandChannelPreserved: `🛟 インタラクション応答を許可するためにコマンドチャンネルが保持されました。`,
            commandChannelNotPreserved: `コマンドチャンネルは保持されませんでした。`,
        },
        cancel: {
            noActive: `現在実行中のバックアップ作成プロセスはありません。`,
            success: `\`{{id}}\`のバックアップ作成がキャンセルされました。`,
        },
        delete: {
            notFound: `指定されたバックアップIDが見つかりません。`,
            alreadyDeleted: `このバックアップは既に削除されています。`,
            success: `バックアップ\`{{id}}\`が削除されました。`,
        },
    },
};
