const emojis = require('./../emojis');

module.exports = {
    test: `هذا نص تجريبي سعودي`,
    timeout: {
        userNotFound: `**${emojis.emojis.incorrect} يالحبيب الآدمي ذا مو موجود عندنا بالسيرفر، يدور غيرنا.**`,
        invalidDuration: `**${emojis.emojis.warning} وش ذا الوقت المضروب؟ حط شي صاحي زي 10m، 1h، 1d.**`,
        durationExceed: `**${emojis.emojis.warning} هيييه! حدك 28 يوم، لا تكثر.**`,
        success: {
            set: `**${emojis.emojis.correct} عطينا {{user}} سكتة لمدة {{duration}} بنجاح. ${emojis.emojis.reason} السالفة: {{reason}}**`,
            remove: `**${emojis.emojis.correct} فكينا التكميم عن {{user}}. ${emojis.emojis.reason} السالفة: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} عيا ينصك ميوت! شيك على صلاحياتي ياخي، وتأكد إني أعلى منه.\n-# إذا نشبت المشكلة، طق باب الدعم.**`,
        cannotSelf: `**${emojis.emojis.warning} صاحي أنت؟ تبي تعطي نفسك ميوت؟**`,
        cannotBot: `**${emojis.emojis.warning} ما عندي صلاحية هاه؟ أماااا تبي تعطيني أنا ميوت زي كذا؟**`,
        cannotHigher: `**${emojis.emojis.warning} معليش، هذا الموظف رتبته زيك أو أعلى منك، مقدر عليه.**`,
        cannotModerate: `**${emojis.emojis.warning} مقدر عليه ذا، رتبته أعلى مني أو معه إداري شقردي.**`,
        invalidAction: `**${emojis.emojis.incorrect} وش قاعد تخبص؟ استخدم 'set' أو 'remove'.**`,
    },
    ban: {
        userNotFound: `**${emojis.emojis.incorrect} الرجال ذا مو في السيرفر أبد.**`,
        success: {
            give: `**${emojis.emojis.correct} طيرنا {{user}} بتبنيدة محترمة. ${emojis.emojis.reason} السالفة: {{reason}}**`,
            remove: `**${emojis.emojis.correct} فكينا الباند عن {{user}}، خله يرجع يتنفس. ${emojis.emojis.reason} السالفة: {{reason}}**`,
        },
        failure: `**${emojis.emojis.incorrect} ما ضبط الباند! تأكد من صلاحياتي ورتبتي إنها فوقه.\n-# إذا عصلجت معك، دق على الدعم الفني.**`,
        cannotSelf: `**${emojis.emojis.warning} تبي تبند نفسك؟ سلامات!**`,
        cannotBot: `**${emojis.emojis.warning} خير تبندني؟ شف سيرفر الدعم يعلمونك الشغل.**`,
        cannotHigher: `**${emojis.emojis.warning} ما تقدر تبند واحد رتبته زيك أو أرفع يا الذيب.**`,
        cannotModerate: `**${emojis.emojis.warning} ما أقدر أطيره، رتبته أعلى مني أو مشرف محنك.**`,
        invalidAction: `**${emojis.emojis.incorrect} لا تألف من راسك، استخدم 'give' أو 'remove'.**`,
        alreadyBanned: `**${emojis.emojis.warning} يا أبوي الرجال مبلوع باند من زمان.**`,
    },
    kick: {
        userNotFound: `**${emojis.emojis.incorrect} ما لقيناه بالسيرفر، شكله شرد.**`,
        kicked: `**${emojis.emojis.correct} دقينا {{user}} بطردة مع الباب. ${emojis.emojis.reason} السالفة: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} عيا ينطرد! تأكد إن رتبتي أعلى منه وصلاحياتي تمام.\n-# إذا ما زان، رح للدعم.**`,
        cannotSelf: `**${emojis.emojis.warning} تبي تطرد نفسك؟ اركد فديتك.**`,
        cannotBot: `**${emojis.emojis.warning} أما تطردني؟ تبطي عظم!**`,
        cannotHigher: `**${emojis.emojis.warning} ما تقدر تطرد واحد زيك أو أعلى منك، دور غيره.**`,
        botCannotHigher: `**${emojis.emojis.warning} ما أقدر أطرد واحد زيك أو أعلى مني.**`,
        cannotModerate: `**${emojis.emojis.warning} معليش ما أقدر عليه، رتبته أعلى مني.**`,
    },
    unban: {
        userNotFound: `**${emojis.emojis.incorrect} يا هوه، هات الأي دي حقه أول.**`,
        userNotBanned: `**${emojis.emojis.warning} الرجال أساساً مو متبند.**`,
        unbanned: `**${emojis.emojis.correct} فكينا قيد {{user}} بنجاح. ${emojis.emojis.reason} السالفة: {{reason}}**`,
        error: `**${emojis.emojis.incorrect} عيا ينفك الباند، الخطأ: {{error}}**`,
    },
    lock: {
        channelNotFound: `**${emojis.emojis.incorrect} القناة مب موجودة، وينها؟**`,
        locked: `**${emojis.emojis.correct} قفشنا {{channel}} بقفل محترم. ${emojis.emojis.reason} السالفة: {{reason}}**`,
        alreadyLocked: `**${emojis.emojis.warning} مسكرة من أول يا شيخ.**`,
        error: `**${emojis.emojis.incorrect} ما رضت تقفل! شيك الصلاحيات تكفى.\n-# إذا معلقة، دور الدعم.**`,
        cannotLock: `**${emojis.emojis.warning} ما أقدر أقفلها، معطيني صلاحيات أنت؟**`,
    },
    unlock: {
        channelNotFound: `**${emojis.emojis.incorrect} أي قناة؟ ترا مب موجودة.**`,
        unlocked: `**${emojis.emojis.correct} فتحنا {{channel}} بنقرة. ${emojis.emojis.reason} السالفة: {{reason}}**`,
        notLocked: `**${emojis.emojis.warning} القناة مفتوحة وتشكي من الفراغ أساساً.**`,
        error: `**${emojis.emojis.incorrect} ما رضت تنفتح! شيك الصلاحيات.\n-# إذا طالت طالت، كلم الدعم.**`,
        cannotUnlock: `**${emojis.emojis.warning} ما أقدر أفتحها، عطني صلاحيات زين أول.**`,
    },

    avatar: {
        onlyInServer: `**${emojis.emojis.warning} يا ولد الأمر ذا بالسيرفرات بس!**`,
        noIcon: `**${emojis.emojis.warning} السيرفر هذا مقرع ماله صورة!**`,
        noAvatar: `**${emojis.emojis.warning} الأخ {{user}} مقرع بدون أفتار!**`,
        avatar: `أفتار الحبيب `,
        requestedBy: `بطلب من الخوي`,
        errorFetching: `**${emojis.emojis.warning} صار لخبطة وما جبنا الصورة!**`,
        invalidUser: `**${emojis.emojis.warning} مستخدم مضروب، تأكد منه!**`,
        type: `شكلها:`,
        icon: `أيقونة سيرفر الـ `,
        avatarTypes: {
            static: `واقفة (PNG)`,
            animated: `ترقص (GIF)`,
        },
        qualityDownload: {
            sd: `حمل الطفشانة (SD)`,
            hd: `حمل الزينة (HD)`,
            uhd: `حمل الخرافية (4K)`,
        },
    },

    banner: {
        onlyInServer: `**${emojis.emojis.warning} الأمر هذا ما يمشي إلا بالسيرفرات!**`,
        noBanner: `**${emojis.emojis.warning} السيرفر عايش عالحديدة ماله بانر!**`,
        banner: `بانر السيرفر حق `,
        requestedBy: `ليون الشاشة:`,
        errorFetching: `**${emojis.emojis.warning} علق النظام وعيا يجيب الصورة!**`,
        invalidUser: `**${emojis.emojis.warning} مستخدم من عالم موازي (غير صالح)!**`,
        type: `شكلها:`,
        accentColor: `لونها:`,
        userBanner: `بانر الكابتن `,
        global: `على الكل`,
        bannerTypes: {
            static: `واقفة (PNG)`,
            animated: `ترقص (GIF)`,
        },
        qualityDownload: {
            sd: `حمل العادية (SD)`,
            hd: `حمل الزينة (HD)`,
            uhd: `حمل الدقة اللي تفلج (4K)`,
        },
    },

    // مشترك / عبارات شائعة
    common: {
        coins: `قرش`,
        captchaFailed: `**${emojis.emojis.warning} الكابتشا طقت وزعلت، حاول مرة ثانية.**`,
        captchaPrompt: `${emojis.emojis.loading} اكتب الخرابيط اللي بالصورة تحت قدامك **{{seconds}} ثانية** بس.`,
        captchaIncorrect: `**${emojis.emojis.warning} لا تكيس! الرمز غلط.**`,
        captchaTimeout: `**${emojis.emojis.warning} نايم طال عمرك؟ خلص الوقت.**`,
        entered: `اللي كتبته`,
        expected: `اللي نبيه`,
        nothing: `ولا شي`,
        noReason: `بدون سالفة`,
        underDevelopment: `**${emojis.emojis.warning} الأمر ذا لسه في الفرن ينطبخ.**`,
    },

    economy: {
        balance: {
            title: `حصالة {{user}}`,
            wallet: `في الجيب`,
            bank: `فالبنك`,
            total: `الورث كله`,
            transactions: `آخر المصاريف`,
            noTransactions: `حصالتك مصفرة مافي حركات.`,
            requestedBy: `بطلب من`,
            cooldown: `الراتب اليومي`,
            ready: `جاهز للزرف!`,
            notReady: `تعال بعد {{time}}`,
        },
        buttons: {
            refresh: `حدث يالطيب`,
            transactions: `الحركات`,
            back: `دحدر ورا`,
            daily: `هات الراتب`,
        },
        transfer: {
            success: `التحويل زان، تم.`,
            recipient: `المستفيد`,
            received: `اللي وصل`,
            tax: `الضريبة (5% شفط)`,
            totalSent: `كل اللي طار منك`,
            insufficient: `طفران يا خوي من وين لك!`,
            invalidAmount: `يا حليلك، حط رقم صاحي فوق الصفر وبدون هللات.`,
            selfTransfer: `التحويل فشل: تسوقها تحول لنفسك؟`,
            botTransfer: `التحويل فشل: البوتات ما تصرف فلوس.`,
            accountTooNew: `معليش وقف، حسابك بالديسكورد لازم يصير عمره 30 يوم عشان تحول.`,
            recipientTooNew: `وقف، خويك حساباته لسه بقراطيسها (أقل من 30 يوم).`,
            insufficientBalance: `طفران طال عمرك.\nرصيدك: **{{balance}}** قرش.`,
            captchaRequired: `لازم كابتشا يا بطل.`,
            captchaChannel: `فشل التحويل: لازم التحقق يكون بشات السيرفر مب بالخاص.`,
            captchaFailed: `فشل التحويل: الصورة تعذرت، جرب ثاني.`,
            captchaTimeout: `التحويل تفركش: نمت وخلص الوقت.`,
            captchaIncorrect: `التحويل تفركش: الرمز غلط يا حول.`,
            captchaHint: `تأكد تكتب الست حروف اللي بالصورة بس وبدون فذلكة.`,
            balanceChanged: `التحويل تفركش: رصيدك لعب فيه جني وتغير وقت التحقق.\nالرصيد الحين: **{{balance}}** قرش.`,
            reason: `السالفة: {{reason}}`,
            // إشعار الرسائل الخاصة
            dmGreetings: [
                `جاك حوالة دسمة بـ {{amount}} قرش فلفرا من {{sender}}`,
                `فلوس فلوس! {{amount}} قرش فلفرا من {{sender}} دخلت حسابك!`,
                `أبشرك! {{sender}} كب عليك {{amount}} قرش فلفرا.`,
                `تنبيييه! {{sender}} حول لك {{amount}} قرش فلفرا، ضبطه.`,
            ],
            dmTransferType: `نوعها: بدون طعم`,
            dmReason: `السالفة`,
        },
        daily: {
            verification: `كابتشا الراتب اليومي`,
            alreadyClaimed: `ساحبها من قبل يا طماع! ارجع بعد **{{time}}**.`,
            success: `تم استلام الراتب، عشت!`,
            received: `قفطت **{{amount}}** قرش.`,
            newBalance: `صار بجيبك: **{{balance}}** قرش.`,
            cancelledIncorrect: `تفركش: الرمز غلط.`,
            cancelledTimeout: `تفركش: خلص وقتك.`,
        },
        reputation: {
            verification: `كابتشا السمعة`,
            cannotBot: `السمعة للرجال مب للبوتات.`,
            cannotSelf: `تسوقها تعطي نفسك سمعة؟`,
            alreadyGiven: `اسمح لنا، مطريت سمعة قريب! ارجع بعد **{{time}}**.`,
            success: `كفو! أعطيت **{{user}}** نقطة سمعة.\nصار عنده **{{count}}** سمعة يشخص بها.`,
            cancelledIncorrect: `تفركش: الرمز غلط.`,
            cancelledTimeout: `تفركش: خلص وقتك.`,
            // إشعار الرسائل الخاصة
            dmReceived: `يا مقيم! جاك تقييم سمعة من {{sender}}!`,
            dmTotal: `صار عندك {{count}} نقطة سمعة.`,
        },
    },

    giveaway: {
        verification: `تأكيد القيف أواي`,
        verificationPrompt: `انقش الحروف اللي بالصورة عشان تمشي بـ **{{action}}**.`,
        verificationFailed: `فشلت يا كابتن.`,
        verificationTimeout: `خلص الوقت يا نايم.`,
        captchaFailed: `كابتشا مضروبة، جرب ثاني.`,
        error: `صار حوسة بالقيف أواي.`,
        start: {
            invalidDuration: `الوقت غلط. جرب: 1d، 2h، 15m، 30s`,
            embedTitle: `🎉 {{prize}}`,
            enterPrompt: `اضغط على 🎉 عشان تدخل وتخرب عليهم!`,
            winners: `الفايزين`,
            host: `المعزب`,
            ends: `يخلص`,
            enterButton: `قط وجهك`,
            footer: `قيف أواي`,
            success: `بدأنا القيف أواي في {{channel}}! حماس!`,
        },
        end: {
            notFound: `ما لقينا القيف أواي ذا بالسيرفر.`,
            notRunning: `القيف أواي قافل أو مفركش خلصنا.`,
            ended: `قضى القيف أواي`,
            endedAnnouncement: `🎉 **قضى القيف أواي!** الفايز(ين) المحظوظين: {{winners}}`,
            noEntrants: `محد قط وجهه وشارك.`,
            none: `ولا أحد`,
            success: `قفلنا القيف أواي بنجاح.`,
        },
        reroll: {
            notFound: `دورت وما لقيت القيف أواي.`,
            notFinished: `انتظر يخلص أول عشان تسوي ريرول.`,
            announcement: `🔄 **ريرول!** فايز(ين) جدد للـ **{{prize}}**: {{winners}}`,
            noEntrants: `محد شارك عشان نختار غيرهم.`,
            success: `تم الريرول بنجاح.`,
        },
        remove: {
            notFound: `مافيه قيف أواي كذا.`,
            success: `شطبنا قيف أواي **{{prize}}** من الداتاات.`,
        },
        list: {
            title: `القيف أوايات الشغالة`,
            noActive: `سيرفر طفران، مافيه قيف أوايات شغالة قبالك.`,
        },
        enter: {
            alreadyEnded: `قضى العرس! القيف أواي ذا مخلص.`,
            alreadyEntered: `نظام تطمع وتشارك مرتين؟ داخل أنت.`,
            success: `🎉 دخلت القيف أواي يا وحش! فالك الفوز.`,
        },
    },

    server: {
        helpMENUtitle: `منيو مساعدة فلفرا`,
        helpMENUdesc: `اختر قسم من تحت عشان تشوف الأوامر اللي تبيض الوجه.`,
        selectCATEGORY: `نقي قسم`,
        selectCOMMAND: `نقي أمر`,
        cmdNAME: `الأمر:`,
        noDescription: `مافيه سيرة ذاتية.`,
        usage: `كيف تستخدمه`,
        category: `القسم`,
        type: `نوعه`,
        cooldown: `فترة نقاهة`,
        none: `مابه شيء`,
        userPerms: `صلاحياتك يا وحش`,
        botPerms: `صلاحياتي أنا`,
        aliases: `أسماء الدلع`,
        info: `الحصيلة: {{slash}} سلاش | {{prefix}} بريفكس`,
        slash: `سلاش`,
        prefix: `بريفكس`,
        push: `دف`,
        and: `و`,
        unknown: `مجهول الهوية`,
        commandNotFOUND: `الأمر \`{{command}}\` غير موجود بقاموسي.`,
        serverINFO: `علوم السيرفر`,
        serverName: `اسم السيرفر`,
        serverID: `الأي دي`,
        owner: `المعزب الكبير`,
        memberCount: `الربع`,
        creationDate: `تاريخ التأسيس`,
        boostLevel: `مستوى الطنخة (البوست)`,
        boosts: `اللفل {{level}} ({{boostsCount}} بوستات)`,
        totalRoles: `الرتب`,
        totalChannels: `الرومات`,
        region: `الديرة`,
        requestedBy: `بطلب من`,
        onlyInServer: `يا حبيبي الأمر ذا للسيرفرات بس!`,
    },

    clear: {
        noTextChannel: `الأمر ذا ما يشتغل إلا بالرومات الكتابية.`,
        title: `ملخص التمسيح`,
        channel: `الروم`,
        requested: `اللي طلبته`,
        filtered: `اللي صفيناه`,
        deleted: `اللي مسحناه بكرامته الأرض`,
        bulk: `خمطة وحدة`,
        singleOld: `حبة حبة (عشانها قديمة)`,
        errors: `فركشات وأخطاء`,
        reason: `السالفة: {{reason}}`,
        deletedNotice: `طيرنا {{count}} رسالة في مهب الريح.`,
        noReason: `بدون سالفة`,
    },

    warn: {
        guildRequired: `لازم تستخدم الأمر ذا بسيرفر يا بطل.`,
        userNotFound: `وين الرجال؟ ما ألمحه.`,
        cannotHigher: `ما تقدر تعطيه إنذار، رتبته تشق جبهتك.`,
        title: `أخذ إنذار محترم`,
        user: `المخالف`,
        infractionId: `رقم القسيمة`,
        activeWarnings: `الإنذارات اللي شغالة`,
        reason: `السالفة`,
        moderator: `العسكري`,
        dmNotice: `جاك إنذار في **{{guild}}**. السالفة: {{reason}} (رقم القسيمة: {{id}})`,
        noReason: `بدون سالفة`,
    },

    warnings: {
        guildRequired: `لازم تستخدم الأمر ذا بسيرفر يا قفطة.`,
        title: `صحيفة سوابق {{user}}`,
        noWarningsActive: `سجله نظيف، مافيه إنذارات شغالة.`,
        noWarningsAll: `يا حليله، ما عنده ولا إنذار.`,
        active: `شغال`,
        inactive: `ملغي`,
        removed: `مشخوط`,
        totalReturned: `كل اللي طلعناه`,
        includingInactive: `مع الملغية بعد`,
        yes: `إيه`,
        no: `لا`,
        requestedBy: `نبشها {{user}}`,
    },

    warnRemove: {
        title: `شطبنا الإنذار`,
        notFound: `أي إنذار تدور عليه؟ ما لقينا شيء.`,
        alreadyInactive: `ميت من زمان هالإنذار.`,
        remainingActive: `كم باقي شغال`,
        userId: `رقم العميل`,
        removalReason: `ليه شلناه`,
        noReason: `بدون سالفة`,
    },

    role: {
        onlyInServer: `هذا الأمر للسيرفرات بس طال عمرك!`,
        mustSpecifyRole: `اختر رتبة تكفى.`,
        userNotFound: `مب موجود بالسيرفر، شكله طفش.`,
        alreadyHasRole: `الرجال مشخص بها من أول، عنده الرتبة.`,
        doesNotHaveRole: `يا ابن الحلال ما عنده هالرتبة أساساً.`,
        giveSuccess: `أعطينا {{user}} رتبة {{role}} ويستاهل. السالفة: {{reason}}`,
        removeSuccess: `شلحنا {{role}} من {{user}}. السالفة: {{reason}}`,
        giveFail: `عيت تجي! شيك صلاحياتي، لازم أكون أعلى من الرتبة اللي بعطيها.\n-# إذا عصلجت قرّش للدعم.`,
        removeFail: `عيت تنشال! تأكد رتبتي أعلى من الرتبة ذي.\n-# إذا قفلت معك كلم الدعم.`,
        giveBotSuccess: `لبسنا {{role}} للـ {{success}} بوت. وفركشت مع {{fail}} بوت. السالفة: {{reason}}`,
        removeBotSuccess: `شلحنا {{role}} من {{success}} بوت. وعيت تنشال من {{fail}} بوت. السالفة: {{reason}}`,
        giveAllSuccess: `وزعنا {{role}} على {{success}} شخص. وسحبنا على {{fail}} السالفة ما. السالفة: {{reason}}`,
        removeAllSuccess: `شلحنا {{role}} من {{success}} شخص. وفركشت مع {{fail}}. السالفة: {{reason}}`,
        mustSpecifyTarget: `حدد مين تبي، إنسان، بوتات، ولا الشعب كله.`,
        noReason: `بدون سالفة`,
    },

    slowmode: {
        noTextChannel: `الروم المستهدف لازم يكون كتابي بس.`,
        invalidDuration: `صيغة الوقت مضروبة. اركد وحط: 10s، 5m، 2h، 1d أو 0 عشان تطفيه.`,
        noChildChannels: `الكيتقري هذا مقطوع من شجرة، مافيه رومات كتابية.`,
        title: `⏱ ضبطنا الوضع السلحفائي (الوضع البطيء)`,
        newRateLimit: `الحد الجديد للدرعمة`,
        channelsUpdated: `الرومات اللي تعدلت`,
        failed: `فشلت`,
        errors: `خربطة`,
        reason: `السالفة: {{reason}}`,
        appliedToCategory: `طبقناها على الفئة: **{{name}}**`,
        channel: `الروم`,
        noReason: `بدون سالفة`,
    },

    nickname: {
        userNotFound: `الرجال ذا ماله أثر بالسيرفر.`,
        cannotSelf: `تسمي نفسك؟ لا يا حبيبي مب من هنا.`,
        cannotBot: `البوت مب للعب، ما تقدر تغير اسمه.`,
        cannotHigher: `حدك! ما تقدر على اللي زيك أو أعلى منك.`,
        cannotModerate: `مقدر أغير اسمه، رتبته تشق وجهي.`,
        successReset: `رجعنا اسم {{user}} زي ما جابته أمه.`,
        successSet: `سمينا {{user}} بـ **{{nickname}}**، عاش الأسامي.`,
        error: `ما ضبطنا تغيير اسم {{user}}: {{error}}`,
    },

    disconnect: {
        no_reason: `بدون سالفة`,
        not_found: `وين الرجال؟ ما أشوفه.`,
        not_in_voice: `جالس يسولف مع جدران، مب بروم صوتي.`,
        owner: `تبي تشوت المعزب؟ صاحي أنت؟`,
        higher_user: `ما تقدر تشوت واحد رتبته زيك أو أعلى منك.`,
        higher_bot: `ما أقدر أشلعه، رتبته فوقي غصن.`,
        user_title: `رونقناه برا الفويس`,
        user_desc: `شحطنا **{user}** برا الصوت.`,
        channel: `الروم`,
        moderator: `المشرف`,
        reason: `السالفة`,
        failed: `عيا يطلع: {error}`,
        invalid_channel: `متأكد هالروم صوتي يا الحبيب؟`,
        empty_channel: `الروم يصفر مافيه أحد.`,
        mass_title: `تصفية جماعية`,
        mass_desc: `كرشنا الكل من **{channel}** ورتحنا.`,
        success: `تم الشوت`,
    },

    addemoji: {
        invalidFileType: `نوع الملف مضروب. يبون بس: {types}`,
        fileTooLarge: `الملف دسم بزيادة. حده: {max}KB`,
        invalidSource: `مصدرك من وين قايله؟ حط رابط أو إيموجي صاحي.`,
        urlInvalidType: `الرابط شكل نهايته غلط. نبي: {types}`,
        fileTooBigRemote: `الرابط جاب لنا فيل. حده: {max}KB`,
        mustProvideSource: `يا خوي عطنا مصدر المصيبة (رابط، إيموجي، ولا ملف).`,
        emojiSuccessTitle: `ركزنا الإيموجي`,
        emojiSuccessDesc: `تم إضافة {emoji} باسم **{name}**، يا حركات!`,
        emojiFail: `عيا يضبط الإيموجي: {error}`,
        missingTags: `عطنا وسوم يونيكود صاحية.`,
        mustProvideSticker: `هات مصدر الملصق (رابط ولا ارفعه).`,
        stickerSuccessTitle: `طبشنا الملصق`,
        stickerSuccessDesc: `تم اللصق **{name}**`,
        stickerFail: `فشل يلزق الملصق: {error}`,
    },

    leveling: {
        underDevelopment: `هذا الأمر باقي يتطبخ، اصبر عليه.`,
        quest: {
            authorTitle: `كدح {{user}} اليومي`,
            title: `مهامك اليومية يالسبع`,
            description: `خلص شغلك اليومي ولقط **XP** و **قروش**!\nشد حيلك وصك الأول بالصدارة! 💪`,
            messagesTitle: `القرقة (الرسائل)`,
            messagesGoal: `الهدف`,
            messagesReward: `الغنيمة`,
            messagesProgress: `التقدم`,
            voiceTitle: `السواليف (الصوت)`,
            voiceGoal: `الهدف`,
            voiceReward: `الغنيمة`,
            voiceProgress: `التقدم`,
            footer: `كرف فلفرا`,
        },
    },

    ping: {
        pinging: `جاري النغزة...`,
        networkError: `نتك أبو كلب متوفي`,
        excellent: `صاروخ`,
        good: `زين يفي بالغرض`,
        high: `لا بأس بطيء شوي`,
        severeLag: `من العصر الحجري`,
        pong: `🏓 بونج!`,
        wsPingTitle: `📡 سرعة الديسكورد البطيخ`,
        msgLatencyTitle: `⏱️ تأخير الرد`,
    },

    backup: {
        error: `صار التماس وتفركش الباك أب، جرب بعدين طال عمرك.`,
        create: {
            title: `أخذنا لك نسخة احتياطية زي اللوز`,
            description: `سيرفرك الحين له باك أب في الحفظ والصون جاهز لأي نكبة.`,
            backupId: `رقم النسخة`,
            rolesCaptured: `الرتب اللي لقطناها`,
            channelsCaptured: `الرومات اللي صورناها`,
            bansCaptured: `المبندين اللي وثقنا قماطهم`,
            archiveSize: `حجم الكارثة`,
            createdAt: `تاريخ اللقطة`,
            createdBy: `بواسطة الذيب {{user}}`,
            failed: `البك أب جاب العيد وفشل. جرب وقت ثاني.`,
        },
        info: {
            title: `تجسس على الباك أب`,
            crossGuild: `النسخة هذي حية بس أنها حقت سيرفر ثاني محترم.`,
            notFound: `النسخة اللي تدورها متبخرة (ما لقيناها).`,
            rolesStored: `الرتب المخزنة`,
            channelsStored: `الرومات المحفوظة`,
            bansStored: `الباندات المخزنة`,
            createdBy: `صاحب العمل`,
            created: `تاريخ الحفظ`,
        },
        list: {
            title: `درج نسخ السيرفر الاحتياطية`,
            noBackups: `يا فقير ما عندك ولا باك أب! اكتب \`/backup create\` وسو لك وحدة.`,
            gettingStarted: `تأمين السيرفر بباك أب دايم يجيب العافية لو طار سيرفرك.`,
            description: `هذي أجدد سوالفك (نسخك):`,
            available: `المتوفّر بالمخزن`,
        },
        load: {
            confirmRequired: `يا صاحبي عطنا \`confirm\` بـ \`true\` عشان نكمل ونسترجع الخرابيط دي.`,
            notFound: `ما لقينا هالنسخة اللي مزعجنا عليها.`,
            unavailable: `النسخة ذي مقفلة للصيانة حالياً. حالتها: {{status}}`,
            empty: `النسخة ذي هوا، مافيها شي نرجعه اساساً.`,
            crossGuildWarning: `انتبه! هالنسخة مهربة من سيرفر ثاني، يمكن نصها ما يركب صح.`,
            title: `ترجيع الباك أب (إنقاذ ما يمكن إنقاذه)`,
            instructions: `نقي وش تبي تسترجع من العفش تحت.`,
            selectPlaceholder: `اختر قشّك (كيفك)`,
            continueBtn: `ادعس`,
            cancelBtn: `بطلنا`,
            canceled: `فركشنا استرجاع الباك أب.`,
            purgeChannels: `قاعد أطير الرومات القديمة، طاطا بطاطا...`,
            purgeRoles: `جاري شطف الرتب...`,
            completedTitle: `رجعنا سيرفرك بالسلامة!`,
            restoredComponents: `العفش اللي رجع`,
            resultsSummary: `كيف الوضع؟`,
            purgeSummary: `كم نضفنا`,
            issues: `العيوب والمطبات اللي قابلتنا`,
            noIssues: `بدون أي مشاكل! ولا كحة!`,
            failed: `**فشل الترجيع يا كابتن**\nضرب فيوز وحنا نرجع. جرب ثانية ولا ابكِ عند الإدارة.`,
            commandChannelContext: `كيف وضع الروم`,
            commandChannelPreserved: `🛟 خليت روم الأوامر عشان لا ينقطع حبل المودة وأرد عليك.`,
            commandChannelNotPreserved: `طيرت روم الأوامر، الله يعوضك.`,
        },
        cancel: {
            noActive: `مافيه باك أب شغال عشان أطفي لك يا حبيبي.`,
            success: `طفينا عملية الباك أب \`{{id}}\`، نم قرير العين.`,
        },
        delete: {
            notFound: `النسخة دي خيال؟ ما لقيناها.`,
            alreadyDeleted: `النسخة مشطوبة من زمان.`,
            success: `تم شطب وحرق النسخة \`{{id}}\`.`,
        },
    },
};
